// Mock data for development and testing

import { UserRole } from '@/constants/roles';
import type { User } from '@/types/auth.types';
import type { Component } from '@/features/components/types';
import { ComponentCategory as ComponentCat, ComponentStatus as CompStatus } from '@/features/components/types';
import type { RawMaterial } from '@/features/raw-materials/types';
import { MaterialCategory, MaterialStatus } from '@/features/raw-materials/types';

// Mock users database
export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'admin@system.com',
    name: 'System Administrator',
    role: UserRole.SYSTEM_ADMIN,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'owner@factory1.com',
    name: 'Rajesh Kumar',
    role: UserRole.INDUSTRY_OWNER,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    email: 'admin@factory1.com',
    name: 'Priya Sharma',
    role: UserRole.ADMINISTRATOR,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: '4',
    email: 'supervisor@factory1.com',
    name: 'Amit Patel',
    role: UserRole.SUPERVISOR,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '5',
    email: 'worker@factory1.com',
    name: 'Vikram Singh',
    role: UserRole.WORKER,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    email: 'owner@factory2.com',
    name: 'Sarah Johnson',
    role: UserRole.INDUSTRY_OWNER,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '7',
    email: 'admin@factory2.com',
    name: 'Michael Chen',
    role: UserRole.ADMINISTRATOR,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '8',
    email: 'supervisor1@factory2.com',
    name: 'Emily Davis',
    role: UserRole.SUPERVISOR,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '9',
    email: 'supervisor2@factory2.com',
    name: 'David Wilson',
    role: UserRole.SUPERVISOR,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: '10',
    email: 'worker1@factory2.com',
    name: 'Maria Garcia',
    role: UserRole.WORKER,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '11',
    email: 'worker2@factory2.com',
    name: 'James Brown',
    role: UserRole.WORKER,
    industryId: 'industry-2',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '12',
    email: 'owner@factory3.com',
    name: 'Anita Desai',
    role: UserRole.INDUSTRY_OWNER,
    industryId: 'industry-3',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '13',
    email: 'admin@factory3.com',
    name: 'Ravi Verma',
    role: UserRole.ADMINISTRATOR,
    industryId: 'industry-3',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '14',
    email: 'supervisor@factory3.com',
    name: 'Jennifer Lee',
    role: UserRole.SUPERVISOR,
    industryId: 'industry-3',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '15',
    email: 'worker1@factory3.com',
    name: 'Robert Taylor',
    role: UserRole.WORKER,
    industryId: 'industry-3',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '16',
    email: 'worker2@factory3.com',
    name: 'Lisa Anderson',
    role: UserRole.WORKER,
    industryId: 'industry-3',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '17',
    email: 'worker3@factory1.com',
    name: 'Suresh Reddy',
    role: UserRole.WORKER,
    industryId: 'industry-1',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '18',
    email: 'worker4@factory1.com',
    name: 'Meena Iyer',
    role: UserRole.WORKER,
    industryId: 'industry-1',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
];

// Mock password (for all users in development)
export const MOCK_PASSWORD = 'password123';

// Helper to generate mock token
export function generateMockToken(userId: string): string {
  return `mock-token-${userId}-${Date.now()}`;
}

// Helper to generate mock refresh token
export function generateMockRefreshToken(userId: string): string {
  return `mock-refresh-${userId}-${Date.now()}`;
}

// Helper to find user by email
export function findUserByEmail(email: string): User | undefined {
  return MOCK_USERS.find((user) => user.email.toLowerCase() === email.toLowerCase());
}

// Helper to find user by id
export function findUserById(id: string): User | undefined {
  return MOCK_USERS.find((user) => user.id === id);
}

// Helper to validate credentials
export function validateCredentials(email: string, password: string): User | null {
  const user = findUserByEmail(email);
  if (user && password === MOCK_PASSWORD) {
    return user;
  }
  return null;
}

// Mock Dashboard Data
import type { DashboardMetrics, ActivityItem, MachineStatusSummary } from '@/features/dashboard/types';
import type { ScheduleTask } from '@/features/schedule/types';

export const MOCK_DASHBOARD_METRICS: Record<UserRole, DashboardMetrics> = {
  [UserRole.SYSTEM_ADMIN]: {
    totalIndustries: 24,
    totalUsers: 156,
    systemUptime: 99.8,
    efficiency: 92,
    trends: {
      machinesTrend: 12.5,
      ordersTrend: 8.3,
      efficiencyTrend: 3.2,
    },
  },
  [UserRole.INDUSTRY_OWNER]: {
    totalMachines: 12,
    activeMachines: 10,
    totalComponents: 48,
    activeOrders: 23,
    completedOrders: 142,
    efficiency: 94,
    trends: {
      machinesTrend: 8.2,
      ordersTrend: 12.5,
      efficiencyTrend: 2.3,
    },
  },
  [UserRole.ADMINISTRATOR]: {
    totalMachines: 12,
    activeOrders: 23,
    pendingMaintenance: 3,
    efficiency: 94,
    trends: {
      ordersTrend: 12.5,
      efficiencyTrend: 2.3,
    },
  },
  [UserRole.SUPERVISOR]: {
    completedTasks: 45,
    activeOrders: 23,
    pendingMaintenance: 3,
    workloadUtilization: 87,
    trends: {
      tasksTrend: 15.2,
    },
  },
  [UserRole.WORKER]: {
    assignedTasks: 8,
    completedTasks: 32,
    efficiency: 96,
    trends: {
      tasksTrend: 12.1,
    },
  },
};

// System Admin activities - platform-level events only
export const MOCK_SYSTEM_ADMIN_ACTIVITIES: ActivityItem[] = [
  {
    id: 'sys-1',
    type: 'system',
    title: 'New industry registered',
    description: 'Automotive Parts Inc. subscribed to Enterprise plan',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-2',
    type: 'system',
    title: 'Subscription renewed',
    description: 'Precision Manufacturing Co. renewed Enterprise subscription',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-3',
    type: 'system',
    title: 'System maintenance completed',
    description: 'Database optimization and backup completed successfully',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-4',
    type: 'user',
    title: 'Industry suspended',
    description: 'ABC Electronics suspended due to payment failure',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System Admin' },
  },
  {
    id: 'sys-5',
    type: 'system',
    title: 'Platform analytics updated',
    description: 'Monthly revenue report generated: $125,000',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-6',
    type: 'system',
    title: 'New feature deployed',
    description: 'Advanced scheduling algorithm v2.0 deployed to all industries',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
];

// Industry Owner activities - industry-wide events
export const MOCK_INDUSTRY_OWNER_ACTIVITIES: ActivityItem[] = [
  {
    id: 'io-1',
    type: 'order',
    title: 'New order received',
    description: 'Order #1245 for 500 units of Component A',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    user: { name: 'Sales Manager' },
  },
  {
    id: 'io-2',
    type: 'machine',
    title: 'Machine productivity alert',
    description: 'CNC Machine #3 achieved 98% efficiency this week',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'io-3',
    type: 'user',
    title: 'New employee onboarded',
    description: 'Administrator account created for Sarah Johnson',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    user: { name: 'Factory Owner' },
  },
  {
    id: 'io-4',
    type: 'maintenance',
    title: 'Maintenance budget updated',
    description: 'Monthly maintenance costs: $12,500',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Finance Manager' },
  },
  {
    id: 'io-5',
    type: 'order',
    title: 'Large order completed',
    description: 'Order #1238 completed - 1000 units delivered',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Production Manager' },
  },
];

// Administrator activities - administrative and user management events
export const MOCK_ADMINISTRATOR_ACTIVITIES: ActivityItem[] = [
  {
    id: 'adm-1',
    type: 'user',
    title: 'New worker added',
    description: 'Worker account created for John Doe',
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-2',
    type: 'user',
    title: 'Shift schedule updated',
    description: 'Night shift schedule modified for 5 workers',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-3',
    type: 'order',
    title: 'Order assignment changed',
    description: 'Order #1242 reassigned to Team B',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-4',
    type: 'machine',
    title: 'Machine permissions updated',
    description: 'Access granted to 3 new operators for CNC Machine #5',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-5',
    type: 'system',
    title: 'Report generated',
    description: 'Weekly productivity report sent to management',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
];

// Supervisor activities - production and machine-related events
export const MOCK_SUPERVISOR_ACTIVITIES: ActivityItem[] = [
  {
    id: 'sup-1',
    type: 'machine',
    title: 'Machine status updated',
    description: 'CNC Machine #3 started production run',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    user: { name: 'Machine Operator' },
  },
  {
    id: 'sup-2',
    type: 'task',
    title: 'Production task completed',
    description: 'Batch #145 completed - 250 units produced',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    user: { name: 'Worker' },
  },
  {
    id: 'sup-3',
    type: 'maintenance',
    title: 'Maintenance scheduled',
    description: 'Scheduled maintenance for Lathe Machine #7',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
  {
    id: 'sup-4',
    type: 'machine',
    title: 'Quality check passed',
    description: 'All units from Machine #2 passed quality inspection',
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Quality Inspector' },
  },
  {
    id: 'sup-5',
    type: 'task',
    title: 'Task assignment updated',
    description: 'Worker reassigned from Machine #4 to Machine #6',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
];

// Worker activities - task-specific events
export const MOCK_WORKER_ACTIVITIES: ActivityItem[] = [
  {
    id: 'wrk-1',
    type: 'task',
    title: 'New task assigned',
    description: 'Produce 100 units of Component A on Machine #1',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
  {
    id: 'wrk-2',
    type: 'task',
    title: 'Task in progress',
    description: 'Current progress: 45/100 units completed',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'wrk-3',
    type: 'task',
    title: 'Task completed',
    description: 'Successfully completed production of 150 units',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Worker' },
  },
  {
    id: 'wrk-4',
    type: 'machine',
    title: 'Machine maintenance required',
    description: 'Machine #3 requires routine maintenance check',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'wrk-5',
    type: 'task',
    title: 'Break time reminder',
    description: 'Scheduled break in 15 minutes',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
];

// Legacy export for backward compatibility (defaults to Industry Owner activities)
export const MOCK_ACTIVITY_ITEMS: ActivityItem[] = MOCK_INDUSTRY_OWNER_ACTIVITIES;

export const MOCK_SCHEDULE_TASKS: ScheduleTask[] = [
  {
    id: 'task-1',
    title: 'Production Task - Precision Gears',
    description: 'Produce 200 units of precision gears for automotive assembly',
    machineId: 'mach-1',
    machineName: 'CNC Machine Alpha',
    componentId: 'comp-1',
    componentName: 'Precision Gear A-100',
    orderId: 'order-1',
    orderNumber: 'ORD-2024-001',
    startTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'high',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 240,
    notes: 'High priority - automotive client deadline',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Production Task - Metal Shafts',
    description: 'Produce 150 metal shafts for industrial equipment',
    machineId: 'mach-2',
    machineName: 'Lathe Machine Beta',
    componentId: 'comp-2',
    componentName: 'Metal Shaft MS-200',
    orderId: 'order-2',
    orderNumber: 'ORD-2024-002',
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'in_progress',
    priority: 'medium',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 180,
    actualDuration: 120,
    notes: 'Currently 60% complete',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Preventive Maintenance - CNC Alpha',
    description: 'Routine maintenance and calibration check',
    machineId: 'mach-1',
    machineName: 'CNC Machine Alpha',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'low',
    assignedTo: '4',
    assignedToName: 'Amit Patel',
    estimatedDuration: 120,
    notes: 'Regular preventive maintenance cycle',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Production Task - Aluminum Brackets',
    description: 'Produce 300 units of aluminum mounting brackets',
    machineId: 'mach-3',
    machineName: 'Milling Machine Gamma',
    componentId: 'comp-3',
    componentName: 'Aluminum Bracket AB-300',
    orderId: 'order-3',
    orderNumber: 'ORD-2024-003',
    startTime: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    priority: 'high',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 240,
    actualDuration: 235,
    notes: 'Completed ahead of schedule',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-5',
    title: 'Urgent Order - Steel Connectors',
    description: 'Rush order for 100 units of steel connectors',
    machineId: 'mach-1',
    machineName: 'CNC Machine Alpha',
    componentId: 'comp-4',
    componentName: 'Steel Connector SC-400',
    orderId: 'order-4',
    orderNumber: 'ORD-2024-004',
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 0.5 * 60 * 60 * 1000).toISOString(),
    status: 'delayed',
    priority: 'critical',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 150,
    actualDuration: 180,
    notes: 'Delayed due to material shortage - now resolved',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-6',
    title: 'Production Task - Hydraulic Components',
    description: 'Produce 80 units of hydraulic valve components',
    machineId: 'mach-4',
    machineName: 'Drill Press Delta',
    componentId: 'comp-5',
    componentName: 'Hydraulic Valve HV-500',
    orderId: 'order-5',
    orderNumber: 'ORD-2024-005',
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'medium',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 240,
    notes: 'Requires precision drilling - extra setup time',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-7',
    title: 'Assembly Task - Motor Housings',
    description: 'Assemble 50 motor housing units',
    machineId: 'mach-5',
    machineName: 'Assembly Line Epsilon',
    componentId: 'comp-6',
    componentName: 'Motor Housing MH-600',
    orderId: 'order-1',
    orderNumber: 'ORD-2024-001',
    startTime: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'high',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 240,
    notes: 'Depends on completion of gear production',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-8',
    title: 'Quality Inspection - Batch #145',
    description: 'Quality control check for completed batch',
    machineId: 'mach-6',
    machineName: 'Inspection Station Zeta',
    startTime: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    priority: 'medium',
    assignedTo: '4',
    assignedToName: 'Amit Patel',
    estimatedDuration: 60,
    actualDuration: 55,
    notes: 'All units passed inspection - 100% quality rate',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-9',
    title: 'Production Task - Bearing Assemblies',
    description: 'Produce 120 bearing assemblies for machinery',
    machineId: 'mach-7',
    machineName: 'Grinding Machine Eta',
    componentId: 'comp-7',
    componentName: 'Bearing Assembly BA-700',
    orderId: 'order-6',
    orderNumber: 'ORD-2024-006',
    startTime: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'low',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 360,
    notes: 'Low priority - flexible deadline',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-10',
    title: 'Production Task - Welded Frames',
    description: 'Weld 40 structural frames for construction equipment',
    machineId: 'mach-8',
    machineName: 'Welding Station Theta',
    componentId: 'comp-8',
    componentName: 'Structural Frame SF-800',
    orderId: 'order-7',
    orderNumber: 'ORD-2024-007',
    startTime: new Date(Date.now() + 30 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 38 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'medium',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 480,
    notes: 'Requires certified welder',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-11',
    title: 'Corrective Maintenance - Lathe Beta',
    description: 'Fix alignment issue on lathe machine',
    machineId: 'mach-2',
    machineName: 'Lathe Machine Beta',
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'high',
    assignedTo: '4',
    assignedToName: 'Amit Patel',
    estimatedDuration: 120,
    notes: 'Minor alignment adjustment needed',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-12',
    title: 'Production Task - Plastic Molds',
    description: 'Create 60 plastic injection molds',
    machineId: 'mach-9',
    machineName: 'Press Machine Iota',
    componentId: 'comp-9',
    componentName: 'Plastic Mold PM-900',
    orderId: 'order-8',
    orderNumber: 'ORD-2024-008',
    startTime: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    priority: 'medium',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 360,
    actualDuration: 355,
    notes: 'Completed on time with excellent quality',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-13',
    title: 'Production Task - Circuit Boards',
    description: 'Assemble 90 electronic circuit boards',
    machineId: 'mach-5',
    machineName: 'Assembly Line Epsilon',
    componentId: 'comp-10',
    componentName: 'Circuit Board CB-1000',
    orderId: 'order-9',
    orderNumber: 'ORD-2024-009',
    startTime: new Date(Date.now() + 42 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'critical',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 360,
    notes: 'Critical client deadline - electronics manufacturer',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-14',
    title: 'Setup Task - New CNC Program',
    description: 'Setup and calibrate new CNC program for specialty parts',
    machineId: 'mach-1',
    machineName: 'CNC Machine Alpha',
    startTime: new Date(Date.now() + 54 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 56 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'low',
    assignedTo: '4',
    assignedToName: 'Amit Patel',
    estimatedDuration: 120,
    notes: 'Preparing for upcoming specialty order',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-15',
    title: 'Production Task - Titanium Parts',
    description: 'Machine 25 titanium aerospace components',
    machineId: 'mach-3',
    machineName: 'Milling Machine Gamma',
    componentId: 'comp-11',
    componentName: 'Titanium Part TP-1100',
    orderId: 'order-10',
    orderNumber: 'ORD-2024-010',
    startTime: new Date(Date.now() + 60 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'critical',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 720,
    notes: 'Aerospace grade - highest precision required',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-16',
    title: 'Cancelled Order - Prototype Parts',
    description: 'Prototype batch cancelled by client',
    machineId: 'mach-7',
    machineName: 'Grinding Machine Eta',
    componentId: 'comp-12',
    componentName: 'Prototype Part PP-1200',
    orderId: 'order-11',
    orderNumber: 'ORD-2024-011',
    startTime: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 42 * 60 * 60 * 1000).toISOString(),
    status: 'cancelled',
    priority: 'low',
    assignedTo: '10',
    assignedToName: 'Maria Garcia',
    estimatedDuration: 360,
    notes: 'Client cancelled order - design changes required',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-17',
    title: 'Production Task - Custom Fasteners',
    description: 'Produce 500 custom fasteners',
    machineId: 'mach-4',
    machineName: 'Drill Press Delta',
    componentId: 'comp-13',
    componentName: 'Custom Fastener CF-1300',
    orderId: 'order-2',
    orderNumber: 'ORD-2024-002',
    startTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    status: 'in_progress',
    priority: 'high',
    assignedTo: '5',
    assignedToName: 'Vikram Singh',
    estimatedDuration: 120,
    actualDuration: 90,
    notes: 'Progress: 75% complete, on track',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const MOCK_MACHINE_STATUS: MachineStatusSummary = {
  running: 7,
  idle: 3,
  maintenance: 1,
  offline: 1,
  total: 12,
  details: [
    {
      id: 'machine-1',
      name: 'CNC Machine #1',
      status: 'running',
      currentTask: 'Production Task - Component A',
      efficiency: 96,
    },
    {
      id: 'machine-2',
      name: 'Lathe Machine #2',
      status: 'running',
      currentTask: 'Production Task - Component B',
      efficiency: 94,
    },
    {
      id: 'machine-3',
      name: 'Drill Press #3',
      status: 'idle',
      efficiency: 0,
    },
    {
      id: 'machine-4',
      name: 'Milling Machine #4',
      status: 'running',
      currentTask: 'Production Task - Component E',
      efficiency: 98,
    },
    {
      id: 'machine-5',
      name: 'Grinder #5',
      status: 'maintenance',
    },
  ],
};

// Helper to get dashboard metrics by role
export function getMockDashboardMetrics(role: UserRole): DashboardMetrics {
  return MOCK_DASHBOARD_METRICS[role] || MOCK_DASHBOARD_METRICS[UserRole.INDUSTRY_OWNER];
}

// Mock Machine Management Data
import type {
  Machine,
  MachineStats,
  MaintenanceRecord,
} from '@/features/machines/types';
import { MachineStatus, MachineType, MaintenanceType, MaintenanceStatus } from '@/features/machines/types';

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'machine-1',
    name: 'CNC Machine #1',
    model: 'CNC-5000X',
    manufacturer: 'Haas Automation',
    type: MachineType.CNC,
    status: MachineStatus.RUNNING,
    capacity: 100,
    location: 'Production Floor A',
    purchaseDate: '2022-01-15',
    installationDate: '2022-02-01',
    warrantyExpiry: '2025-01-15',
    lastMaintenanceDate: '2024-09-15',
    nextMaintenanceDate: '2024-12-15',
    description: 'High-precision CNC machining center for complex parts',
    specifications: {
      maxSpindleSpeed: 12000,
      toolCapacity: 24,
      workAreaX: 1000,
      workAreaY: 500,
      workAreaZ: 500,
      power: 15,
    },
    industryId: 'industry-1',
    createdAt: '2022-01-15T10:00:00Z',
    updatedAt: '2024-10-20T14:30:00Z',
    metrics: {
      utilization: 87,
      efficiency: 94,
      totalRuntime: 5240,
      totalDowntime: 120,
      averageUptime: 97.8,
      mtbf: 720,
      mttr: 4,
      productionCount: 12450,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-2',
    name: 'Lathe Machine #2',
    model: 'LT-2500',
    manufacturer: 'DMG MORI',
    type: MachineType.LATHE,
    status: MachineStatus.RUNNING,
    capacity: 80,
    location: 'Production Floor A',
    purchaseDate: '2021-06-20',
    installationDate: '2021-07-10',
    warrantyExpiry: '2024-06-20',
    lastMaintenanceDate: '2024-08-22',
    nextMaintenanceDate: '2024-11-22',
    description: 'Precision lathe for turning operations',
    specifications: {
      maxSpindleSpeed: 8000,
      maxTurningDiameter: 450,
      maxTurningLength: 1000,
      power: 11,
    },
    industryId: 'industry-1',
    createdAt: '2021-06-20T09:00:00Z',
    updatedAt: '2024-10-20T15:00:00Z',
    metrics: {
      utilization: 82,
      efficiency: 91,
      totalRuntime: 7850,
      totalDowntime: 180,
      averageUptime: 97.7,
      mtbf: 680,
      mttr: 5,
      productionCount: 18220,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-3',
    name: 'Drill Press #3',
    model: 'DP-1000',
    manufacturer: 'Makino',
    type: MachineType.DRILL,
    status: MachineStatus.IDLE,
    capacity: 60,
    location: 'Production Floor B',
    purchaseDate: '2020-03-10',
    installationDate: '2020-04-01',
    lastMaintenanceDate: '2024-10-10',
    nextMaintenanceDate: '2025-01-10',
    description: 'Industrial drilling machine for precision holes',
    specifications: {
      maxDrillDiameter: 50,
      spindleTravel: 300,
      power: 7.5,
    },
    industryId: 'industry-1',
    createdAt: '2020-03-10T11:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
    metrics: {
      utilization: 65,
      efficiency: 88,
      totalRuntime: 9120,
      totalDowntime: 210,
      averageUptime: 97.7,
      mtbf: 650,
      mttr: 6,
      productionCount: 24500,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-4',
    name: 'Milling Machine #4',
    model: 'VM-3000',
    manufacturer: 'Okuma',
    type: MachineType.MILL,
    status: MachineStatus.RUNNING,
    capacity: 90,
    location: 'Production Floor A',
    purchaseDate: '2022-08-15',
    installationDate: '2022-09-01',
    warrantyExpiry: '2025-08-15',
    lastMaintenanceDate: '2024-09-30',
    nextMaintenanceDate: '2024-12-30',
    description: 'Vertical milling machine for complex geometries',
    specifications: {
      maxSpindleSpeed: 10000,
      toolCapacity: 20,
      tableSize: '1500x600',
      power: 12,
    },
    industryId: 'industry-1',
    createdAt: '2022-08-15T13:00:00Z',
    updatedAt: '2024-10-20T16:00:00Z',
    metrics: {
      utilization: 90,
      efficiency: 96,
      totalRuntime: 4200,
      totalDowntime: 80,
      averageUptime: 98.1,
      mtbf: 750,
      mttr: 3,
      productionCount: 9800,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-5',
    name: 'Grinder #5',
    model: 'SG-800',
    manufacturer: 'Studer',
    type: MachineType.GRINDER,
    status: MachineStatus.MAINTENANCE,
    capacity: 50,
    location: 'Production Floor B',
    purchaseDate: '2019-11-20',
    installationDate: '2019-12-15',
    lastMaintenanceDate: '2024-10-18',
    nextMaintenanceDate: '2024-10-25',
    description: 'Surface grinding machine for finishing operations',
    specifications: {
      grindingWheel: 400,
      tableSize: '800x400',
      power: 9,
    },
    industryId: 'industry-1',
    createdAt: '2019-11-20T10:00:00Z',
    updatedAt: '2024-10-18T08:00:00Z',
    metrics: {
      utilization: 75,
      efficiency: 89,
      totalRuntime: 11200,
      totalDowntime: 280,
      averageUptime: 97.5,
      mtbf: 600,
      mttr: 7,
      productionCount: 32000,
      lastProductionDate: '2024-10-17',
    },
  },
  {
    id: 'machine-6',
    name: 'Press Machine #6',
    model: 'HP-500',
    manufacturer: 'Schuler',
    type: MachineType.PRESS,
    status: MachineStatus.RUNNING,
    capacity: 120,
    location: 'Production Floor C',
    purchaseDate: '2023-02-10',
    installationDate: '2023-03-01',
    warrantyExpiry: '2026-02-10',
    lastMaintenanceDate: '2024-10-05',
    nextMaintenanceDate: '2025-01-05',
    description: 'Hydraulic press for stamping and forming',
    specifications: {
      pressureCapacity: 500,
      strokeLength: 300,
      bedSize: '1200x800',
      power: 22,
    },
    industryId: 'industry-1',
    createdAt: '2023-02-10T12:00:00Z',
    updatedAt: '2024-10-20T17:00:00Z',
    metrics: {
      utilization: 85,
      efficiency: 93,
      totalRuntime: 3100,
      totalDowntime: 60,
      averageUptime: 98.1,
      mtbf: 800,
      mttr: 2,
      productionCount: 15600,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-7',
    name: 'Welding Machine #7',
    model: 'WM-350',
    manufacturer: 'Lincoln Electric',
    type: MachineType.WELDING,
    status: MachineStatus.IDLE,
    capacity: 70,
    location: 'Assembly Area',
    purchaseDate: '2021-09-15',
    installationDate: '2021-10-01',
    warrantyExpiry: '2024-09-15',
    lastMaintenanceDate: '2024-09-01',
    nextMaintenanceDate: '2024-12-01',
    description: 'Robotic welding station for automated joining',
    specifications: {
      weldingCurrent: 350,
      dutyCycle: 100,
      power: 18,
    },
    industryId: 'industry-1',
    createdAt: '2021-09-15T14:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
    metrics: {
      utilization: 72,
      efficiency: 90,
      totalRuntime: 6850,
      totalDowntime: 150,
      averageUptime: 97.9,
      mtbf: 700,
      mttr: 4,
      productionCount: 8900,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-8',
    name: 'Cutting Machine #8',
    model: 'LC-6000',
    manufacturer: 'Bystronic',
    type: MachineType.CUTTING,
    status: MachineStatus.RUNNING,
    capacity: 95,
    location: 'Production Floor C',
    purchaseDate: '2022-11-20',
    installationDate: '2022-12-10',
    warrantyExpiry: '2025-11-20',
    lastMaintenanceDate: '2024-09-20',
    nextMaintenanceDate: '2024-12-20',
    description: 'Laser cutting machine for sheet metal',
    specifications: {
      laserPower: 6000,
      cuttingArea: '3000x1500',
      maxThickness: 25,
      power: 30,
    },
    industryId: 'industry-1',
    createdAt: '2022-11-20T10:00:00Z',
    updatedAt: '2024-10-20T15:30:00Z',
    metrics: {
      utilization: 88,
      efficiency: 95,
      totalRuntime: 3950,
      totalDowntime: 70,
      averageUptime: 98.2,
      mtbf: 780,
      mttr: 3,
      productionCount: 11200,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-9',
    name: 'Assembly Line #9',
    model: 'AL-2000',
    manufacturer: 'Bosch Rexroth',
    type: MachineType.ASSEMBLY,
    status: MachineStatus.RUNNING,
    capacity: 150,
    location: 'Assembly Area',
    purchaseDate: '2023-05-10',
    installationDate: '2023-06-01',
    warrantyExpiry: '2026-05-10',
    lastMaintenanceDate: '2024-10-01',
    nextMaintenanceDate: '2025-01-01',
    description: 'Automated assembly line for product assembly',
    specifications: {
      lineSpeed: 20,
      stations: 12,
      power: 25,
    },
    industryId: 'industry-1',
    createdAt: '2023-05-10T09:00:00Z',
    updatedAt: '2024-10-20T18:00:00Z',
    metrics: {
      utilization: 92,
      efficiency: 97,
      totalRuntime: 2800,
      totalDowntime: 40,
      averageUptime: 98.6,
      mtbf: 850,
      mttr: 2,
      productionCount: 42000,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-10',
    name: 'Packaging Machine #10',
    model: 'PM-1500',
    manufacturer: 'Ishida',
    type: MachineType.PACKAGING,
    status: MachineStatus.RUNNING,
    capacity: 110,
    location: 'Packaging Area',
    purchaseDate: '2023-08-15',
    installationDate: '2023-09-01',
    warrantyExpiry: '2026-08-15',
    lastMaintenanceDate: '2024-10-10',
    nextMaintenanceDate: '2025-01-10',
    description: 'Automated packaging system for finished products',
    specifications: {
      packagingSpeed: 150,
      bagSize: '100-500g',
      power: 12,
    },
    industryId: 'industry-1',
    createdAt: '2023-08-15T11:00:00Z',
    updatedAt: '2024-10-20T16:30:00Z',
    metrics: {
      utilization: 86,
      efficiency: 94,
      totalRuntime: 2400,
      totalDowntime: 50,
      averageUptime: 98.0,
      mtbf: 820,
      mttr: 2,
      productionCount: 36000,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-11',
    name: 'CNC Machine #11',
    model: 'CNC-3000',
    manufacturer: 'Mazak',
    type: MachineType.CNC,
    status: MachineStatus.IDLE,
    capacity: 85,
    location: 'Production Floor A',
    purchaseDate: '2020-12-10',
    installationDate: '2021-01-15',
    lastMaintenanceDate: '2024-08-15',
    nextMaintenanceDate: '2024-11-15',
    description: 'Multi-axis CNC machine for precision parts',
    specifications: {
      maxSpindleSpeed: 10000,
      toolCapacity: 20,
      axes: 5,
      power: 13,
    },
    industryId: 'industry-1',
    createdAt: '2020-12-10T10:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
    metrics: {
      utilization: 78,
      efficiency: 92,
      totalRuntime: 8200,
      totalDowntime: 200,
      averageUptime: 97.6,
      mtbf: 680,
      mttr: 5,
      productionCount: 16500,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-12',
    name: 'Test Machine #12',
    model: 'TEST-100',
    manufacturer: 'Generic',
    type: MachineType.OTHER,
    status: MachineStatus.OFFLINE,
    capacity: 40,
    location: 'Storage',
    purchaseDate: '2018-05-20',
    description: 'Reserved for testing and development',
    industryId: 'industry-1',
    createdAt: '2018-05-20T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
    metrics: {
      utilization: 0,
      efficiency: 0,
      totalRuntime: 0,
      totalDowntime: 0,
      averageUptime: 0,
      productionCount: 0,
    },
  },
];

export const MOCK_MACHINE_STATS: MachineStats = {
  total: 12,
  running: 7,
  idle: 3,
  maintenance: 1,
  offline: 1,
  averageUtilization: 83.5,
  averageEfficiency: 92.4,
};

export const MOCK_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    machineId: 'machine-1',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-09-15',
    completedDate: '2024-09-15',
    description: 'Routine preventive maintenance - lubrication and inspection',
    performedBy: 'Maintenance Team A',
    cost: 500,
    notes: 'All systems operating normally',
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-09-15T16:00:00Z',
  },
  {
    id: 'maint-2',
    machineId: 'machine-1',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-12-15',
    description: 'Scheduled quarterly maintenance',
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'maint-3',
    machineId: 'machine-2',
    type: MaintenanceType.CORRECTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-08-22',
    completedDate: '2024-08-22',
    description: 'Spindle bearing replacement',
    performedBy: 'Maintenance Team B',
    cost: 1200,
    notes: 'Bearing replaced, machine recalibrated',
    createdAt: '2024-08-20T09:00:00Z',
    updatedAt: '2024-08-22T17:00:00Z',
  },
  {
    id: 'maint-4',
    machineId: 'machine-5',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.IN_PROGRESS,
    scheduledDate: '2024-10-18',
    description: 'Grinding wheel replacement and alignment',
    performedBy: 'Maintenance Team A',
    createdAt: '2024-10-10T10:00:00Z',
    updatedAt: '2024-10-18T08:00:00Z',
  },
  {
    id: 'maint-5',
    machineId: 'machine-5',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-25',
    description: 'Post-maintenance inspection and testing',
    createdAt: '2024-10-18T10:00:00Z',
    updatedAt: '2024-10-18T10:00:00Z',
  },
  {
    id: 'maint-6',
    machineId: 'machine-4',
    type: MaintenanceType.EMERGENCY,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-07-10',
    completedDate: '2024-07-10',
    description: 'Emergency repair - coolant leak',
    performedBy: 'Maintenance Team C',
    cost: 800,
    notes: 'Coolant hose replaced, system tested',
    createdAt: '2024-07-10T14:00:00Z',
    updatedAt: '2024-07-10T18:00:00Z',
  },
  {
    id: 'maint-7',
    machineId: 'machine-3',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-09-05',
    completedDate: '2024-09-05',
    description: 'Oil change and filter replacement',
    performedBy: 'Maintenance Team B',
    cost: 350,
    notes: 'Routine service completed successfully',
    createdAt: '2024-08-25T10:00:00Z',
    updatedAt: '2024-09-05T14:00:00Z',
  },
  {
    id: 'maint-8',
    machineId: 'machine-6',
    type: MaintenanceType.CORRECTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-08-15',
    completedDate: '2024-08-16',
    description: 'Hydraulic pump repair',
    performedBy: 'Maintenance Team C',
    cost: 2500,
    notes: 'Pump replaced, pressure tested',
    createdAt: '2024-08-14T09:00:00Z',
    updatedAt: '2024-08-16T16:30:00Z',
  },
  {
    id: 'maint-9',
    machineId: 'machine-7',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-28',
    description: 'Monthly inspection and cleaning',
    performedBy: 'Maintenance Team A',
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'maint-10',
    machineId: 'machine-8',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-07-20',
    completedDate: '2024-07-20',
    description: 'Calibration and alignment check',
    performedBy: 'Maintenance Team B',
    cost: 650,
    notes: 'All measurements within tolerance',
    createdAt: '2024-07-10T10:00:00Z',
    updatedAt: '2024-07-20T15:00:00Z',
  },
  {
    id: 'maint-11',
    machineId: 'machine-2',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-10',
    description: 'Scheduled weekly maintenance',
    createdAt: '2024-10-05T10:00:00Z',
    updatedAt: '2024-10-21T10:00:00Z',
  },
  {
    id: 'maint-12',
    machineId: 'machine-9',
    type: MaintenanceType.EMERGENCY,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-09-28',
    completedDate: '2024-09-28',
    description: 'Power supply failure repair',
    performedBy: 'Maintenance Team C',
    cost: 1800,
    notes: 'Power unit replaced, system restored',
    createdAt: '2024-09-28T11:00:00Z',
    updatedAt: '2024-09-28T17:00:00Z',
  },
  {
    id: 'maint-13',
    machineId: 'machine-10',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-11-05',
    description: 'Quarterly preventive maintenance',
    performedBy: 'Maintenance Team A',
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
  },
  {
    id: 'maint-14',
    machineId: 'machine-11',
    type: MaintenanceType.CORRECTIVE,
    status: MaintenanceStatus.IN_PROGRESS,
    scheduledDate: '2024-10-21',
    description: 'Tool holder mechanism repair',
    performedBy: 'Maintenance Team B',
    createdAt: '2024-10-20T08:00:00Z',
    updatedAt: '2024-10-21T09:00:00Z',
  },
  {
    id: 'maint-15',
    machineId: 'machine-4',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-30',
    description: 'Monthly lubrication and inspection',
    performedBy: 'Maintenance Team A',
    createdAt: '2024-10-18T10:00:00Z',
    updatedAt: '2024-10-18T10:00:00Z',
  },
  {
    id: 'maint-16',
    machineId: 'machine-1',
    type: MaintenanceType.CORRECTIVE,
    status: MaintenanceStatus.CANCELLED,
    scheduledDate: '2024-09-10',
    description: 'Sensor replacement',
    notes: 'Issue resolved without sensor replacement',
    createdAt: '2024-09-08T10:00:00Z',
    updatedAt: '2024-09-09T14:00:00Z',
  },
  {
    id: 'maint-17',
    machineId: 'machine-3',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-11-12',
    description: 'Annual comprehensive inspection',
    performedBy: 'Maintenance Team C',
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'maint-18',
    machineId: 'machine-6',
    type: MaintenanceType.EMERGENCY,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-18',
    description: 'Control panel malfunction',
    createdAt: '2024-10-18T13:00:00Z',
    updatedAt: '2024-10-21T10:00:00Z',
  },
];

// ====================
// SYSTEM ADMIN DATA
// ====================

// Industries
import type {
  Industry,
  Subscription,
  PlatformAnalytics,
  PlatformMetrics,
  SubscriptionDistribution,
  RevenueData,
  IndustryGrowth,
  TopIndustry,
} from '@/features/system/types';
import { IndustryStatus, SubscriptionPlan, SubscriptionStatus } from '@/features/system/types';

export const MOCK_INDUSTRIES: Industry[] = [
  {
    id: 'industry-1',
    name: 'Precision Manufacturing Co.',
    description: 'High-precision CNC machining and manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.ENTERPRISE,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Factory Owner',
    adminEmail: 'owner@factory1.com',
    phoneNumber: '+1-555-0101',
    address: '123 Industrial Avenue',
    city: 'Detroit',
    state: 'Michigan',
    country: 'USA',
    postalCode: '48201',
    employeeCount: 156,
    machineCount: 12,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
    expiryDate: '2025-01-15T00:00:00Z',
  },
  {
    id: 'industry-2',
    name: 'AutoTech Industries',
    description: 'Automotive parts manufacturing and assembly',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.PROFESSIONAL,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'John Smith',
    adminEmail: 'admin@autotech.com',
    phoneNumber: '+1-555-0102',
    address: '456 Manufacturing Blvd',
    city: 'Chicago',
    state: 'Illinois',
    country: 'USA',
    postalCode: '60601',
    employeeCount: 98,
    machineCount: 8,
    createdAt: '2023-03-20T08:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
    expiryDate: '2025-03-20T00:00:00Z',
  },
  {
    id: 'industry-3',
    name: 'Metal Works Ltd.',
    description: 'Metal fabrication and welding services',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.BASIC,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Sarah Johnson',
    adminEmail: 'admin@metalworks.com',
    phoneNumber: '+1-555-0103',
    address: '789 Steel Street',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'USA',
    postalCode: '15201',
    employeeCount: 45,
    machineCount: 5,
    createdAt: '2023-06-10T08:00:00Z',
    updatedAt: '2024-08-20T10:00:00Z',
    expiryDate: '2025-06-10T00:00:00Z',
  },
  {
    id: 'industry-4',
    name: 'Tech Components Inc.',
    description: 'Electronic component manufacturing',
    status: IndustryStatus.SUSPENDED,
    subscriptionPlan: SubscriptionPlan.PROFESSIONAL,
    subscriptionStatus: SubscriptionStatus.PAYMENT_PENDING,
    adminName: 'Michael Chen',
    adminEmail: 'admin@techcomponents.com',
    phoneNumber: '+1-555-0104',
    address: '321 Tech Park',
    city: 'San Jose',
    state: 'California',
    country: 'USA',
    postalCode: '95101',
    employeeCount: 72,
    machineCount: 6,
    createdAt: '2023-08-05T08:00:00Z',
    updatedAt: '2024-10-10T10:00:00Z',
    expiryDate: '2024-08-05T00:00:00Z',
  },
  {
    id: 'industry-5',
    name: 'Aerospace Solutions',
    description: 'Aerospace component manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.ENTERPRISE,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Robert Williams',
    adminEmail: 'admin@aerospace.com',
    phoneNumber: '+1-555-0105',
    address: '555 Aviation Way',
    city: 'Seattle',
    state: 'Washington',
    country: 'USA',
    postalCode: '98101',
    employeeCount: 210,
    machineCount: 15,
    createdAt: '2022-11-01T08:00:00Z',
    updatedAt: '2024-09-25T10:00:00Z',
    expiryDate: '2025-11-01T00:00:00Z',
  },
  {
    id: 'industry-6',
    name: 'Polymer Products',
    description: 'Plastic injection molding and manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.BASIC,
    subscriptionStatus: SubscriptionStatus.TRIAL,
    adminName: 'Emily Davis',
    adminEmail: 'admin@polymer.com',
    phoneNumber: '+1-555-0106',
    address: '888 Polymer Lane',
    city: 'Houston',
    state: 'Texas',
    country: 'USA',
    postalCode: '77001',
    employeeCount: 38,
    machineCount: 4,
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
    expiryDate: '2024-10-15T00:00:00Z',
  },
];

// Subscriptions
export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    industryId: 'industry-1',
    industryName: 'Precision Manufacturing Co.',
    plan: SubscriptionPlan.ENTERPRISE,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-01-15T00:00:00Z',
    endDate: '2025-01-15T00:00:00Z',
    maxUsers: 200,
    maxMachines: 50,
    maxStorage: 1000,
    currentUsers: 156,
    currentMachines: 12,
    currentStorage: 234,
    features: [
      'Unlimited Users',
      'Advanced Analytics',
      'Priority Support',
      'Custom Integrations',
      'API Access',
      'White Label',
    ],
    price: 999,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'sub-2',
    industryId: 'industry-2',
    industryName: 'AutoTech Industries',
    plan: SubscriptionPlan.PROFESSIONAL,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-03-20T00:00:00Z',
    endDate: '2025-03-20T00:00:00Z',
    maxUsers: 100,
    maxMachines: 25,
    maxStorage: 500,
    currentUsers: 98,
    currentMachines: 8,
    currentStorage: 156,
    features: [
      'Up to 100 Users',
      'Standard Analytics',
      'Email Support',
      'API Access',
    ],
    price: 499,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-03-20T08:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'sub-3',
    industryId: 'industry-3',
    industryName: 'Metal Works Ltd.',
    plan: SubscriptionPlan.BASIC,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-06-10T00:00:00Z',
    endDate: '2025-06-10T00:00:00Z',
    maxUsers: 50,
    maxMachines: 10,
    maxStorage: 100,
    currentUsers: 45,
    currentMachines: 5,
    currentStorage: 42,
    features: [
      'Up to 50 Users',
      'Basic Analytics',
      'Email Support',
    ],
    price: 199,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-06-10T08:00:00Z',
    updatedAt: '2024-08-20T10:00:00Z',
  },
  {
    id: 'sub-4',
    industryId: 'industry-4',
    industryName: 'Tech Components Inc.',
    plan: SubscriptionPlan.PROFESSIONAL,
    status: SubscriptionStatus.PAYMENT_PENDING,
    startDate: '2023-08-05T00:00:00Z',
    endDate: '2024-08-05T00:00:00Z',
    maxUsers: 100,
    maxMachines: 25,
    maxStorage: 500,
    currentUsers: 72,
    currentMachines: 6,
    currentStorage: 89,
    features: [
      'Up to 100 Users',
      'Standard Analytics',
      'Email Support',
      'API Access',
    ],
    price: 499,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: false,
    createdAt: '2023-08-05T08:00:00Z',
    updatedAt: '2024-10-10T10:00:00Z',
  },
  {
    id: 'sub-5',
    industryId: 'industry-5',
    industryName: 'Aerospace Solutions',
    plan: SubscriptionPlan.ENTERPRISE,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-11-01T00:00:00Z',
    endDate: '2025-11-01T00:00:00Z',
    maxUsers: 200,
    maxMachines: 50,
    maxStorage: 1000,
    currentUsers: 210,
    currentMachines: 15,
    currentStorage: 456,
    features: [
      'Unlimited Users',
      'Advanced Analytics',
      'Priority Support',
      'Custom Integrations',
      'API Access',
      'White Label',
    ],
    price: 999,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2022-11-01T08:00:00Z',
    updatedAt: '2024-09-25T10:00:00Z',
  },
  {
    id: 'sub-6',
    industryId: 'industry-6',
    industryName: 'Polymer Products',
    plan: SubscriptionPlan.BASIC,
    status: SubscriptionStatus.TRIAL,
    startDate: '2024-09-15T00:00:00Z',
    endDate: '2024-10-15T00:00:00Z',
    maxUsers: 50,
    maxMachines: 10,
    maxStorage: 100,
    currentUsers: 38,
    currentMachines: 4,
    currentStorage: 12,
    features: [
      'Up to 50 Users',
      'Basic Analytics',
      'Email Support',
    ],
    price: 0,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: false,
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
];

// Platform Analytics
const platformMetrics: PlatformMetrics = {
  totalIndustries: 6,
  activeIndustries: 5,
  totalUsers: 619,
  totalMachines: 50,
  totalRevenue: 189420,
  monthlyRevenue: 3196,
  totalStorage: 989,
  totalOrders: 1247,
};

const subscriptionDistribution: SubscriptionDistribution[] = [
  {
    plan: SubscriptionPlan.FREE,
    count: 0,
    percentage: 0,
    revenue: 0,
  },
  {
    plan: SubscriptionPlan.BASIC,
    count: 2,
    percentage: 33.3,
    revenue: 398,
  },
  {
    plan: SubscriptionPlan.PROFESSIONAL,
    count: 2,
    percentage: 33.3,
    revenue: 998,
  },
  {
    plan: SubscriptionPlan.ENTERPRISE,
    count: 2,
    percentage: 33.3,
    revenue: 1998,
  },
];

const revenueData: RevenueData[] = [
  { month: 'Jan', revenue: 15680, subscriptions: 4 },
  { month: 'Feb', revenue: 16240, subscriptions: 4 },
  { month: 'Mar', revenue: 18790, subscriptions: 5 },
  { month: 'Apr', revenue: 17650, subscriptions: 5 },
  { month: 'May', revenue: 19230, subscriptions: 5 },
  { month: 'Jun', revenue: 21450, subscriptions: 6 },
  { month: 'Jul', revenue: 19870, subscriptions: 6 },
  { month: 'Aug', revenue: 18340, subscriptions: 5 },
  { month: 'Sep', revenue: 20560, subscriptions: 6 },
  { month: 'Oct', revenue: 19180, subscriptions: 6 },
  { month: 'Nov', revenue: 16240, subscriptions: 5 },
  { month: 'Dec', revenue: 15680, subscriptions: 5 },
];

const industryGrowth: IndustryGrowth[] = [
  { month: 'Jan', newIndustries: 0, activeIndustries: 4, churnedIndustries: 0 },
  { month: 'Feb', newIndustries: 0, activeIndustries: 4, churnedIndustries: 0 },
  { month: 'Mar', newIndustries: 1, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'Apr', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'May', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'Jun', newIndustries: 1, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Jul', newIndustries: 0, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Aug', newIndustries: 0, activeIndustries: 5, churnedIndustries: 1 },
  { month: 'Sep', newIndustries: 1, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Oct', newIndustries: 0, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Nov', newIndustries: 0, activeIndustries: 5, churnedIndustries: 1 },
  { month: 'Dec', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
];

const topIndustries: TopIndustry[] = [
  {
    id: 'industry-5',
    name: 'Aerospace Solutions',
    plan: SubscriptionPlan.ENTERPRISE,
    users: 210,
    machines: 15,
    revenue: 11988,
  },
  {
    id: 'industry-1',
    name: 'Precision Manufacturing Co.',
    plan: SubscriptionPlan.ENTERPRISE,
    users: 156,
    machines: 12,
    revenue: 11988,
  },
  {
    id: 'industry-2',
    name: 'AutoTech Industries',
    plan: SubscriptionPlan.PROFESSIONAL,
    users: 98,
    machines: 8,
    revenue: 5988,
  },
  {
    id: 'industry-4',
    name: 'Tech Components Inc.',
    plan: SubscriptionPlan.PROFESSIONAL,
    users: 72,
    machines: 6,
    revenue: 5988,
  },
  {
    id: 'industry-3',
    name: 'Metal Works Ltd.',
    plan: SubscriptionPlan.BASIC,
    users: 45,
    machines: 5,
    revenue: 2388,
  },
];

export const MOCK_PLATFORM_ANALYTICS: PlatformAnalytics = {
  metrics: platformMetrics,
  subscriptionDistribution,
  revenueData,
  industryGrowth,
  topIndustries,
};

// ========================================
// COMPONENTS
// ========================================

export const MOCK_COMPONENTS: Component[] = [
  {
    id: 'comp-1',
    name: 'Precision Bearing',
    code: 'BRG-001',
    description: 'High-precision ball bearing for CNC machines',
    category: ComponentCat.MECHANICAL,
    status: CompStatus.IN_STOCK,
    unit: 'piece',
    quantityInStock: 150,
    reorderLevel: 50,
    unitPrice: 25.50,
    supplier: 'Bearing Inc.',
    leadTimeDays: 7,
    specifications: {
      diameter: '25mm',
      material: 'Steel',
      loadRating: '5000N',
    },
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Control PCB',
    code: 'PCB-001',
    description: 'Main control board for automated systems',
    category: ComponentCat.ELECTRONIC,
    status: CompStatus.IN_STOCK,
    unit: 'piece',
    quantityInStock: 45,
    reorderLevel: 20,
    unitPrice: 145.00,
    supplier: 'Electronics Corp.',
    leadTimeDays: 14,
    specifications: {
      voltage: '24V DC',
      dimensions: '150x100mm',
      certification: 'CE, RoHS',
    },
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Hydraulic Cylinder',
    code: 'HYD-001',
    description: 'Heavy-duty hydraulic cylinder assembly',
    category: ComponentCat.ASSEMBLY,
    status: CompStatus.LOW_STOCK,
    unit: 'piece',
    quantityInStock: 12,
    reorderLevel: 15,
    unitPrice: 320.00,
    supplier: 'Hydraulics Ltd.',
    leadTimeDays: 21,
    specifications: {
      boreSize: '80mm',
      stroke: '500mm',
      pressure: '250 bar',
    },
    createdAt: new Date('2024-01-05').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Servo Motor',
    code: 'MTR-001',
    description: 'High-torque servo motor for precision control',
    category: ComponentCat.ELECTRONIC,
    status: CompStatus.IN_STOCK,
    unit: 'piece',
    quantityInStock: 28,
    reorderLevel: 10,
    unitPrice: 275.00,
    supplier: 'MotorTech Inc.',
    leadTimeDays: 10,
    specifications: {
      power: '1.5kW',
      voltage: '220V AC',
      rpm: '3000',
      torque: '5Nm',
    },
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'comp-5',
    name: 'Gear Assembly',
    code: 'GR-001',
    description: 'Precision gear set for transmission systems',
    category: ComponentCat.ASSEMBLY,
    status: CompStatus.IN_STOCK,
    unit: 'set',
    quantityInStock: 65,
    reorderLevel: 25,
    unitPrice: 89.50,
    supplier: 'Gear Works Co.',
    leadTimeDays: 12,
    specifications: {
      ratio: '1:10',
      material: 'Hardened Steel',
      teeth: '40',
    },
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'comp-6',
    name: 'Custom Bracket',
    code: 'BRK-001',
    description: 'Custom-manufactured mounting bracket',
    category: ComponentCat.CUSTOM,
    status: CompStatus.OUT_OF_STOCK,
    unit: 'piece',
    quantityInStock: 0,
    reorderLevel: 30,
    unitPrice: 45.00,
    supplier: 'Custom Parts Ltd.',
    leadTimeDays: 28,
    specifications: {
      material: 'Aluminum Alloy',
      finish: 'Anodized',
      weight: '0.5kg',
    },
    createdAt: new Date('2024-01-25').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'comp-7',
    name: 'Proximity Sensor',
    code: 'SNS-001',
    description: 'Inductive proximity sensor for position detection',
    category: ComponentCat.ELECTRONIC,
    status: CompStatus.IN_STOCK,
    unit: 'piece',
    quantityInStock: 95,
    reorderLevel: 40,
    unitPrice: 35.00,
    supplier: 'Sensor Systems',
    leadTimeDays: 5,
    specifications: {
      type: 'Inductive',
      range: '8mm',
      voltage: '12-24V DC',
    },
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: 'comp-8',
    name: 'Timing Belt',
    code: 'BLT-001',
    description: 'Reinforced timing belt for synchronous drives',
    category: ComponentCat.MECHANICAL,
    status: CompStatus.LOW_STOCK,
    unit: 'meter',
    quantityInStock: 18,
    reorderLevel: 25,
    unitPrice: 12.50,
    supplier: 'Belt Dynamics',
    leadTimeDays: 7,
    specifications: {
      width: '25mm',
      pitch: '5mm',
      material: 'Rubber with steel core',
    },
    createdAt: new Date('2024-01-30').toISOString(),
    updatedAt: new Date('2024-02-12').toISOString(),
  },
];

// ========================================
// RAW MATERIALS
// ========================================

export const MOCK_RAW_MATERIALS: RawMaterial[] = [
  {
    id: 'mat-1',
    name: 'Steel Sheet - Grade 304',
    code: 'STL-304-01',
    description: 'Stainless steel sheet 304 grade for metal fabrication',
    category: MaterialCategory.METAL,
    status: MaterialStatus.IN_STOCK,
    unit: 'kg',
    quantity: 2500,
    reorderLevel: 500,
    unitCost: 8.50,
    supplier: 'MetalCorp Industries',
    supplierContact: 'sales@metalcorp.com',
    leadTimeDays: 10,
    storageLocation: 'Warehouse A - Section 1',
    specifications: {
      thickness: '2mm',
      grade: '304',
      finish: 'Mill Finish',
      width: '1220mm',
      length: '2440mm',
    },
    lastRestocked: '2024-10-01T10:00:00Z',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'mat-2',
    name: 'Aluminum Bar - 6061',
    code: 'ALU-6061-01',
    description: 'Aluminum alloy bar 6061 for machining',
    category: MaterialCategory.METAL,
    status: MaterialStatus.IN_STOCK,
    unit: 'kg',
    quantity: 1800,
    reorderLevel: 400,
    unitCost: 6.75,
    supplier: 'Aluminum Solutions Ltd.',
    supplierContact: 'orders@alusolutions.com',
    leadTimeDays: 7,
    storageLocation: 'Warehouse A - Section 2',
    specifications: {
      diameter: '50mm',
      alloy: '6061-T6',
      length: '6000mm',
      temper: 'T6',
    },
    lastRestocked: '2024-09-28T14:00:00Z',
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-09-28T14:00:00Z',
  },
  {
    id: 'mat-3',
    name: 'ABS Plastic Pellets',
    code: 'PLS-ABS-01',
    description: 'High-impact ABS plastic pellets for injection molding',
    category: MaterialCategory.PLASTIC,
    status: MaterialStatus.IN_STOCK,
    unit: 'kg',
    quantity: 850,
    reorderLevel: 300,
    unitCost: 3.20,
    supplier: 'Polymer Supply Co.',
    supplierContact: 'info@polymersupply.com',
    leadTimeDays: 14,
    storageLocation: 'Warehouse B - Section 1',
    specifications: {
      type: 'ABS',
      grade: 'High Impact',
      color: 'Natural',
      meltFlow: '22 g/10min',
    },
    lastRestocked: '2024-10-05T11:00:00Z',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-10-05T11:00:00Z',
  },
  {
    id: 'mat-4',
    name: 'Industrial Cutting Oil',
    code: 'CHM-OIL-01',
    description: 'Synthetic cutting oil for CNC machining operations',
    category: MaterialCategory.CHEMICAL,
    status: MaterialStatus.LOW_STOCK,
    unit: 'liter',
    quantity: 180,
    reorderLevel: 200,
    unitCost: 12.50,
    supplier: 'ChemTech Solutions',
    supplierContact: 'sales@chemtech.com',
    leadTimeDays: 5,
    storageLocation: 'Chemical Storage - Zone A',
    specifications: {
      type: 'Synthetic',
      viscosity: '32 cSt',
      flashPoint: '220°C',
      biodegradable: 'Yes',
    },
    lastRestocked: '2024-09-15T09:00:00Z',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-10-15T16:00:00Z',
  },
  {
    id: 'mat-5',
    name: 'Hardwood Plywood',
    code: 'WOD-PLY-01',
    description: 'Marine grade hardwood plywood sheets',
    category: MaterialCategory.WOOD,
    status: MaterialStatus.IN_STOCK,
    unit: 'sheet',
    quantity: 120,
    reorderLevel: 30,
    unitCost: 45.00,
    supplier: 'Timber & Wood Supplies',
    supplierContact: 'orders@timberwood.com',
    leadTimeDays: 12,
    storageLocation: 'Warehouse C - Dry Storage',
    specifications: {
      thickness: '18mm',
      grade: 'Marine Grade',
      size: '1220x2440mm',
      layers: '9 ply',
    },
    lastRestocked: '2024-10-10T13:00:00Z',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-10-10T13:00:00Z',
  },
  {
    id: 'mat-6',
    name: 'Silicon Rubber Sheet',
    code: 'RUB-SIL-01',
    description: 'Food-grade silicon rubber sheets for gasket production',
    category: MaterialCategory.RUBBER,
    status: MaterialStatus.IN_STOCK,
    unit: 'kg',
    quantity: 420,
    reorderLevel: 100,
    unitCost: 18.00,
    supplier: 'Rubber Industries Inc.',
    supplierContact: 'sales@rubberind.com',
    leadTimeDays: 15,
    storageLocation: 'Warehouse B - Section 3',
    specifications: {
      thickness: '3mm',
      grade: 'Food Grade',
      hardness: '60 Shore A',
      temperature: '-60°C to 230°C',
    },
    lastRestocked: '2024-09-20T10:00:00Z',
    createdAt: '2024-02-05T08:00:00Z',
    updatedAt: '2024-09-20T10:00:00Z',
  },
  {
    id: 'mat-7',
    name: 'Carbon Fiber Fabric',
    code: 'CMP-CF-01',
    description: 'Woven carbon fiber fabric for composite parts',
    category: MaterialCategory.COMPOSITE,
    status: MaterialStatus.LOW_STOCK,
    unit: 'meter',
    quantity: 45,
    reorderLevel: 50,
    unitCost: 85.00,
    supplier: 'Advanced Composites Ltd.',
    supplierContact: 'info@advcomposites.com',
    leadTimeDays: 21,
    storageLocation: 'Warehouse C - Climate Control',
    specifications: {
      weave: '2x2 Twill',
      weight: '200 g/m²',
      width: '1000mm',
      carbonContent: '100%',
    },
    lastRestocked: '2024-08-25T12:00:00Z',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-10-18T15:00:00Z',
  },
  {
    id: 'mat-8',
    name: 'Epoxy Resin',
    code: 'CHM-EPX-01',
    description: 'Two-part epoxy resin system for bonding and coating',
    category: MaterialCategory.CHEMICAL,
    status: MaterialStatus.OUT_OF_STOCK,
    unit: 'kg',
    quantity: 0,
    reorderLevel: 150,
    unitCost: 22.00,
    supplier: 'ChemTech Solutions',
    supplierContact: 'sales@chemtech.com',
    leadTimeDays: 10,
    storageLocation: 'Chemical Storage - Zone B',
    specifications: {
      type: 'Two-part',
      mixRatio: '2:1',
      potLife: '45 minutes',
      cureTime: '24 hours',
    },
    lastRestocked: '2024-07-15T10:00:00Z',
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
  },
  {
    id: 'mat-9',
    name: 'Copper Wire',
    code: 'MTL-COP-01',
    description: 'Bare copper wire for electrical applications',
    category: MaterialCategory.METAL,
    status: MaterialStatus.IN_STOCK,
    unit: 'kg',
    quantity: 650,
    reorderLevel: 200,
    unitCost: 15.50,
    supplier: 'MetalCorp Industries',
    supplierContact: 'sales@metalcorp.com',
    leadTimeDays: 8,
    storageLocation: 'Warehouse A - Section 3',
    specifications: {
      diameter: '2.5mm',
      purity: '99.99%',
      conductivity: '100% IACS',
      standard: 'ASTM B1',
    },
    lastRestocked: '2024-10-12T11:00:00Z',
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-10-12T11:00:00Z',
  },
  {
    id: 'mat-10',
    name: 'Industrial Fabric',
    code: 'TXT-FAB-01',
    description: 'Heavy-duty polyester fabric for industrial use',
    category: MaterialCategory.TEXTILE,
    status: MaterialStatus.ORDERED,
    unit: 'meter',
    quantity: 280,
    reorderLevel: 150,
    unitCost: 9.50,
    supplier: 'Textile Industries Co.',
    supplierContact: 'orders@textileind.com',
    leadTimeDays: 18,
    storageLocation: 'Warehouse C - Section 2',
    specifications: {
      material: 'Polyester',
      weight: '500 g/m²',
      width: '1500mm',
      strength: '1200N',
    },
    lastRestocked: '2024-09-05T14:00:00Z',
    createdAt: '2024-02-25T08:00:00Z',
    updatedAt: '2024-10-16T10:00:00Z',
  },
];

// ========================================
// ORDERS
// ========================================

import type { Order, OrderStats } from '@/features/orders/types';
import { OrderStatus as OrdStatus, OrderPriority } from '@/features/orders/types';

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-2024-001',
    customer: {
      name: 'TechCorp Industries',
      email: 'procurement@techcorp.com',
      phone: '+1-555-1001',
      company: 'TechCorp Industries Inc.',
    },
    items: [
      {
        componentId: 'comp-1',
        componentName: 'Precision Bearing',
        componentCode: 'BRG-001',
        quantity: 100,
        unitPrice: 25.50,
        totalPrice: 2550.00,
      },
      {
        componentId: 'comp-4',
        componentName: 'Servo Motor',
        componentCode: 'MTR-001',
        quantity: 10,
        unitPrice: 275.00,
        totalPrice: 2750.00,
      },
    ],
    totalQuantity: 110,
    totalAmount: 5300.00,
    status: OrdStatus.IN_PROGRESS,
    priority: OrderPriority.HIGH,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-1',
    assignedMachineName: 'CNC Machine #1',
    notes: 'Priority customer - ensure quality standards',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-2024-002',
    customer: {
      name: 'AutoMotive Solutions',
      email: 'orders@autosol.com',
      phone: '+1-555-1002',
      company: 'AutoMotive Solutions LLC',
    },
    items: [
      {
        componentId: 'comp-5',
        componentName: 'Gear Assembly',
        componentCode: 'GR-001',
        quantity: 50,
        unitPrice: 89.50,
        totalPrice: 4475.00,
      },
    ],
    totalQuantity: 50,
    totalAmount: 4475.00,
    status: OrdStatus.PENDING,
    priority: OrderPriority.MEDIUM,
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Standard delivery schedule',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-3',
    orderNumber: 'ORD-2024-003',
    customer: {
      name: 'Industrial Equipment Co.',
      email: 'purchasing@indequip.com',
      phone: '+1-555-1003',
      company: 'Industrial Equipment Co.',
    },
    items: [
      {
        componentId: 'comp-3',
        componentName: 'Hydraulic Cylinder',
        componentCode: 'HYD-001',
        quantity: 5,
        unitPrice: 320.00,
        totalPrice: 1600.00,
      },
      {
        componentId: 'comp-7',
        componentName: 'Proximity Sensor',
        componentCode: 'SNS-001',
        quantity: 20,
        unitPrice: 35.00,
        totalPrice: 700.00,
      },
    ],
    totalQuantity: 25,
    totalAmount: 2300.00,
    status: OrdStatus.COMPLETED,
    priority: OrderPriority.MEDIUM,
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-4',
    assignedMachineName: 'Milling Machine #4',
    notes: 'Completed ahead of schedule',
    industryId: 'industry-1',
    createdBy: 'supervisor@factory1.com',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-4',
    orderNumber: 'ORD-2024-004',
    customer: {
      name: 'MegaFactory Ltd.',
      email: 'orders@megafactory.com',
      phone: '+1-555-1004',
      company: 'MegaFactory Ltd.',
    },
    items: [
      {
        componentId: 'comp-2',
        componentName: 'Control PCB',
        componentCode: 'PCB-001',
        quantity: 30,
        unitPrice: 145.00,
        totalPrice: 4350.00,
      },
      {
        componentId: 'comp-7',
        componentName: 'Proximity Sensor',
        componentCode: 'SNS-001',
        quantity: 60,
        unitPrice: 35.00,
        totalPrice: 2100.00,
      },
    ],
    totalQuantity: 90,
    totalAmount: 6450.00,
    status: OrdStatus.IN_PROGRESS,
    priority: OrderPriority.URGENT,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-2',
    assignedMachineName: 'Lathe Machine #2',
    notes: 'Rush order - expedite processing',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-5',
    orderNumber: 'ORD-2024-005',
    customer: {
      name: 'Precision Parts Inc.',
      email: 'contact@precisionparts.com',
      phone: '+1-555-1005',
      company: 'Precision Parts Inc.',
    },
    items: [
      {
        componentId: 'comp-1',
        componentName: 'Precision Bearing',
        componentCode: 'BRG-001',
        quantity: 200,
        unitPrice: 25.50,
        totalPrice: 5100.00,
      },
    ],
    totalQuantity: 200,
    totalAmount: 5100.00,
    status: OrdStatus.ON_HOLD,
    priority: OrderPriority.LOW,
    dueDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Waiting for customer confirmation on specifications',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-6',
    orderNumber: 'ORD-2024-006',
    customer: {
      name: 'Global Manufacturing',
      email: 'procurement@globalmfg.com',
      phone: '+1-555-1006',
      company: 'Global Manufacturing Corp.',
    },
    items: [
      {
        componentId: 'comp-6',
        componentName: 'Custom Bracket',
        componentCode: 'BRK-001',
        quantity: 150,
        unitPrice: 45.00,
        totalPrice: 6750.00,
      },
    ],
    totalQuantity: 150,
    totalAmount: 6750.00,
    status: OrdStatus.PENDING,
    priority: OrderPriority.HIGH,
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Custom parts - verify design before production',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-7',
    orderNumber: 'ORD-2024-007',
    customer: {
      name: 'FastTrack Systems',
      email: 'orders@fasttrack.com',
      phone: '+1-555-1007',
      company: 'FastTrack Systems Inc.',
    },
    items: [
      {
        componentId: 'comp-8',
        componentName: 'Timing Belt',
        componentCode: 'BLT-001',
        quantity: 100,
        unitPrice: 12.50,
        totalPrice: 1250.00,
      },
      {
        componentId: 'comp-1',
        componentName: 'Precision Bearing',
        componentCode: 'BRG-001',
        quantity: 50,
        unitPrice: 25.50,
        totalPrice: 1275.00,
      },
    ],
    totalQuantity: 150,
    totalAmount: 2525.00,
    status: OrdStatus.COMPLETED,
    priority: OrderPriority.MEDIUM,
    dueDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-6',
    assignedMachineName: 'Press Machine #6',
    notes: 'Standard order - completed on time',
    industryId: 'industry-1',
    createdBy: 'supervisor@factory1.com',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-8',
    orderNumber: 'ORD-2024-008',
    customer: {
      name: 'Elite Components',
      email: 'purchasing@elitecomp.com',
      phone: '+1-555-1008',
      company: 'Elite Components LLC',
    },
    items: [
      {
        componentId: 'comp-4',
        componentName: 'Servo Motor',
        componentCode: 'MTR-001',
        quantity: 25,
        unitPrice: 275.00,
        totalPrice: 6875.00,
      },
    ],
    totalQuantity: 25,
    totalAmount: 6875.00,
    status: OrdStatus.CANCELLED,
    priority: OrderPriority.LOW,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Cancelled by customer - project scope changed',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-9',
    orderNumber: 'ORD-2024-009',
    customer: {
      name: 'Dynamic Engineering',
      email: 'orders@dynamiceng.com',
      phone: '+1-555-1009',
      company: 'Dynamic Engineering Group',
    },
    items: [
      {
        componentId: 'comp-5',
        componentName: 'Gear Assembly',
        componentCode: 'GR-001',
        quantity: 75,
        unitPrice: 89.50,
        totalPrice: 6712.50,
      },
      {
        componentId: 'comp-3',
        componentName: 'Hydraulic Cylinder',
        componentCode: 'HYD-001',
        quantity: 8,
        unitPrice: 320.00,
        totalPrice: 2560.00,
      },
    ],
    totalQuantity: 83,
    totalAmount: 9272.50,
    status: OrdStatus.PENDING,
    priority: OrderPriority.MEDIUM,
    dueDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Large order - schedule production accordingly',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-10',
    orderNumber: 'ORD-2024-010',
    customer: {
      name: 'Superior Manufacturing',
      email: 'procurement@superiormfg.com',
      phone: '+1-555-1010',
      company: 'Superior Manufacturing Inc.',
    },
    items: [
      {
        componentId: 'comp-2',
        componentName: 'Control PCB',
        componentCode: 'PCB-001',
        quantity: 40,
        unitPrice: 145.00,
        totalPrice: 5800.00,
      },
      {
        componentId: 'comp-4',
        componentName: 'Servo Motor',
        componentCode: 'MTR-001',
        quantity: 15,
        unitPrice: 275.00,
        totalPrice: 4125.00,
      },
      {
        componentId: 'comp-7',
        componentName: 'Proximity Sensor',
        componentCode: 'SNS-001',
        quantity: 80,
        unitPrice: 35.00,
        totalPrice: 2800.00,
      },
    ],
    totalQuantity: 135,
    totalAmount: 12725.00,
    status: OrdStatus.IN_PROGRESS,
    priority: OrderPriority.HIGH,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-8',
    assignedMachineName: 'Cutting Machine #8',
    notes: 'High-value order - priority production',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-11',
    orderNumber: 'ORD-2024-011',
    customer: {
      name: 'Quantum Industries',
      email: 'orders@quantumind.com',
      phone: '+1-555-1011',
      company: 'Quantum Industries Corp.',
    },
    items: [
      {
        componentId: 'comp-1',
        componentName: 'Precision Bearing',
        componentCode: 'BRG-001',
        quantity: 120,
        unitPrice: 25.50,
        totalPrice: 3060.00,
      },
      {
        componentId: 'comp-8',
        componentName: 'Timing Belt',
        componentCode: 'BLT-001',
        quantity: 60,
        unitPrice: 12.50,
        totalPrice: 750.00,
      },
    ],
    totalQuantity: 180,
    totalAmount: 3810.00,
    status: OrdStatus.COMPLETED,
    priority: OrderPriority.LOW,
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedMachineId: 'machine-4',
    assignedMachineName: 'Milling Machine #4',
    notes: 'Standard order completed successfully',
    industryId: 'industry-1',
    createdBy: 'supervisor@factory1.com',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'order-12',
    orderNumber: 'ORD-2024-012',
    customer: {
      name: 'NextGen Solutions',
      email: 'procurement@nextgen.com',
      phone: '+1-555-1012',
      company: 'NextGen Solutions Ltd.',
    },
    items: [
      {
        componentId: 'comp-5',
        componentName: 'Gear Assembly',
        componentCode: 'GR-001',
        quantity: 100,
        unitPrice: 89.50,
        totalPrice: 8950.00,
      },
    ],
    totalQuantity: 100,
    totalAmount: 8950.00,
    status: OrdStatus.PENDING,
    priority: OrderPriority.URGENT,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Urgent requirement - allocate resources immediately',
    industryId: 'industry-1',
    createdBy: 'admin@factory1.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ORDER_STATS: OrderStats = {
  total: 12,
  pending: 4,
  inProgress: 3,
  completed: 3,
  cancelled: 1,
  onHold: 1,
  totalRevenue: 75342.50,
  averageOrderValue: 6278.54,
};
