// Mock data for development and testing

import { UserRole } from '@/constants/roles';
import type { User } from '@/types/auth.types';

// Mock users database
export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'admin@system.com',
    name: 'System Administrator',
    role: UserRole.SYSTEM_ADMIN,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'owner@factory1.com',
    name: 'Factory Owner',
    role: UserRole.INDUSTRY_OWNER,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    email: 'admin@factory1.com',
    name: 'Factory Admin',
    role: UserRole.ADMINISTRATOR,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    email: 'supervisor@factory1.com',
    name: 'Production Supervisor',
    role: UserRole.SUPERVISOR,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    email: 'worker@factory1.com',
    name: 'Machine Operator',
    role: UserRole.WORKER,
    industryId: 'industry-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Mock password (for all users in development)
export const MOCK_PASSWORD = 'password123';

// Helper to generate mock token
export function generateMockToken(userId: string): string {
  return `mock-token-${userId}-${Date.now()}`;
}

// Helper to generate mock refresh token
export function generateMockRefreshToken(userId: string): string {
  return `mock-refresh-${userId}-${Date.now()}`;
}

// Helper to find user by email
export function findUserByEmail(email: string): User | undefined {
  return MOCK_USERS.find((user) => user.email.toLowerCase() === email.toLowerCase());
}

// Helper to find user by id
export function findUserById(id: string): User | undefined {
  return MOCK_USERS.find((user) => user.id === id);
}

// Helper to validate credentials
export function validateCredentials(email: string, password: string): User | null {
  const user = findUserByEmail(email);
  if (user && password === MOCK_PASSWORD) {
    return user;
  }
  return null;
}

// Mock Dashboard Data
import type { DashboardMetrics, ActivityItem, ScheduleTask, MachineStatusSummary } from '@/features/dashboard/types';

export const MOCK_DASHBOARD_METRICS: Record<UserRole, DashboardMetrics> = {
  [UserRole.SYSTEM_ADMIN]: {
    totalIndustries: 24,
    totalUsers: 156,
    systemUptime: 99.8,
    efficiency: 92,
    trends: {
      machinesTrend: 12.5,
      ordersTrend: 8.3,
      efficiencyTrend: 3.2,
    },
  },
  [UserRole.INDUSTRY_OWNER]: {
    totalMachines: 12,
    activeMachines: 10,
    totalComponents: 48,
    activeOrders: 23,
    completedOrders: 142,
    efficiency: 94,
    trends: {
      machinesTrend: 8.2,
      ordersTrend: 12.5,
      efficiencyTrend: 2.3,
    },
  },
  [UserRole.ADMINISTRATOR]: {
    totalMachines: 12,
    activeOrders: 23,
    pendingMaintenance: 3,
    efficiency: 94,
    trends: {
      ordersTrend: 12.5,
      efficiencyTrend: 2.3,
    },
  },
  [UserRole.SUPERVISOR]: {
    completedTasks: 45,
    activeOrders: 23,
    pendingMaintenance: 3,
    workloadUtilization: 87,
    trends: {
      tasksTrend: 15.2,
    },
  },
  [UserRole.WORKER]: {
    assignedTasks: 8,
    completedTasks: 32,
    efficiency: 96,
    trends: {
      tasksTrend: 12.1,
    },
  },
};

// System Admin activities - platform-level events only
export const MOCK_SYSTEM_ADMIN_ACTIVITIES: ActivityItem[] = [
  {
    id: 'sys-1',
    type: 'system',
    title: 'New industry registered',
    description: 'Automotive Parts Inc. subscribed to Enterprise plan',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-2',
    type: 'system',
    title: 'Subscription renewed',
    description: 'Precision Manufacturing Co. renewed Enterprise subscription',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-3',
    type: 'system',
    title: 'System maintenance completed',
    description: 'Database optimization and backup completed successfully',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-4',
    type: 'user',
    title: 'Industry suspended',
    description: 'ABC Electronics suspended due to payment failure',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System Admin' },
  },
  {
    id: 'sys-5',
    type: 'system',
    title: 'Platform analytics updated',
    description: 'Monthly revenue report generated: $125,000',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'sys-6',
    type: 'system',
    title: 'New feature deployed',
    description: 'Advanced scheduling algorithm v2.0 deployed to all industries',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
];

// Industry Owner activities - industry-wide events
export const MOCK_INDUSTRY_OWNER_ACTIVITIES: ActivityItem[] = [
  {
    id: 'io-1',
    type: 'order',
    title: 'New order received',
    description: 'Order #1245 for 500 units of Component A',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    user: { name: 'Sales Manager' },
  },
  {
    id: 'io-2',
    type: 'machine',
    title: 'Machine productivity alert',
    description: 'CNC Machine #3 achieved 98% efficiency this week',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'io-3',
    type: 'user',
    title: 'New employee onboarded',
    description: 'Administrator account created for Sarah Johnson',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    user: { name: 'Factory Owner' },
  },
  {
    id: 'io-4',
    type: 'maintenance',
    title: 'Maintenance budget updated',
    description: 'Monthly maintenance costs: $12,500',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Finance Manager' },
  },
  {
    id: 'io-5',
    type: 'order',
    title: 'Large order completed',
    description: 'Order #1238 completed - 1000 units delivered',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Production Manager' },
  },
];

// Administrator activities - administrative and user management events
export const MOCK_ADMINISTRATOR_ACTIVITIES: ActivityItem[] = [
  {
    id: 'adm-1',
    type: 'user',
    title: 'New worker added',
    description: 'Worker account created for John Doe',
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-2',
    type: 'user',
    title: 'Shift schedule updated',
    description: 'Night shift schedule modified for 5 workers',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-3',
    type: 'order',
    title: 'Order assignment changed',
    description: 'Order #1242 reassigned to Team B',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-4',
    type: 'machine',
    title: 'Machine permissions updated',
    description: 'Access granted to 3 new operators for CNC Machine #5',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
  {
    id: 'adm-5',
    type: 'system',
    title: 'Report generated',
    description: 'Weekly productivity report sent to management',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Admin' },
  },
];

// Supervisor activities - production and machine-related events
export const MOCK_SUPERVISOR_ACTIVITIES: ActivityItem[] = [
  {
    id: 'sup-1',
    type: 'machine',
    title: 'Machine status updated',
    description: 'CNC Machine #3 started production run',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    user: { name: 'Machine Operator' },
  },
  {
    id: 'sup-2',
    type: 'task',
    title: 'Production task completed',
    description: 'Batch #145 completed - 250 units produced',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    user: { name: 'Worker' },
  },
  {
    id: 'sup-3',
    type: 'maintenance',
    title: 'Maintenance scheduled',
    description: 'Scheduled maintenance for Lathe Machine #7',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
  {
    id: 'sup-4',
    type: 'machine',
    title: 'Quality check passed',
    description: 'All units from Machine #2 passed quality inspection',
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Quality Inspector' },
  },
  {
    id: 'sup-5',
    type: 'task',
    title: 'Task assignment updated',
    description: 'Worker reassigned from Machine #4 to Machine #6',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
];

// Worker activities - task-specific events
export const MOCK_WORKER_ACTIVITIES: ActivityItem[] = [
  {
    id: 'wrk-1',
    type: 'task',
    title: 'New task assigned',
    description: 'Produce 100 units of Component A on Machine #1',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    user: { name: 'Production Supervisor' },
  },
  {
    id: 'wrk-2',
    type: 'task',
    title: 'Task in progress',
    description: 'Current progress: 45/100 units completed',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'wrk-3',
    type: 'task',
    title: 'Task completed',
    description: 'Successfully completed production of 150 units',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: { name: 'Factory Worker' },
  },
  {
    id: 'wrk-4',
    type: 'machine',
    title: 'Machine maintenance required',
    description: 'Machine #3 requires routine maintenance check',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
  {
    id: 'wrk-5',
    type: 'task',
    title: 'Break time reminder',
    description: 'Scheduled break in 15 minutes',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    user: { name: 'System' },
  },
];

// Legacy export for backward compatibility (defaults to Industry Owner activities)
export const MOCK_ACTIVITY_ITEMS: ActivityItem[] = MOCK_INDUSTRY_OWNER_ACTIVITIES;

export const MOCK_SCHEDULE_TASKS: ScheduleTask[] = [
  {
    id: '1',
    title: 'Production Task - Component A',
    description: 'Produce 200 units of Component A',
    machineId: 'machine-1',
    machineName: 'CNC Machine #1',
    componentId: 'comp-a',
    componentName: 'Component A',
    startTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'high',
    assignedTo: 'worker-1',
  },
  {
    id: '2',
    title: 'Production Task - Component B',
    description: 'Produce 150 units of Component B',
    machineId: 'machine-2',
    machineName: 'Lathe Machine #2',
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'in_progress',
    priority: 'medium',
    assignedTo: 'worker-2',
  },
  {
    id: '3',
    title: 'Maintenance Task',
    description: 'Routine maintenance check',
    machineId: 'machine-3',
    machineName: 'Drill Press #3',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    priority: 'low',
  },
  {
    id: '4',
    title: 'Production Task - Component C',
    description: 'Produce 300 units of Component C',
    machineId: 'machine-4',
    machineName: 'Milling Machine #4',
    startTime: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    priority: 'high',
    assignedTo: 'worker-3',
  },
  {
    id: '5',
    title: 'Urgent Order - Component D',
    description: 'Rush order for 100 units',
    machineId: 'machine-1',
    machineName: 'CNC Machine #1',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    status: 'overdue',
    priority: 'high',
    assignedTo: 'worker-1',
  },
];

export const MOCK_MACHINE_STATUS: MachineStatusSummary = {
  running: 7,
  idle: 3,
  maintenance: 1,
  offline: 1,
  total: 12,
  details: [
    {
      id: 'machine-1',
      name: 'CNC Machine #1',
      status: 'running',
      currentTask: 'Production Task - Component A',
      efficiency: 96,
    },
    {
      id: 'machine-2',
      name: 'Lathe Machine #2',
      status: 'running',
      currentTask: 'Production Task - Component B',
      efficiency: 94,
    },
    {
      id: 'machine-3',
      name: 'Drill Press #3',
      status: 'idle',
      efficiency: 0,
    },
    {
      id: 'machine-4',
      name: 'Milling Machine #4',
      status: 'running',
      currentTask: 'Production Task - Component E',
      efficiency: 98,
    },
    {
      id: 'machine-5',
      name: 'Grinder #5',
      status: 'maintenance',
    },
  ],
};

// Helper to get dashboard metrics by role
export function getMockDashboardMetrics(role: UserRole): DashboardMetrics {
  return MOCK_DASHBOARD_METRICS[role] || MOCK_DASHBOARD_METRICS[UserRole.INDUSTRY_OWNER];
}

// Mock Machine Management Data
import type {
  Machine,
  MachineStats,
  MaintenanceRecord,
} from '@/features/machines/types';
import { MachineStatus, MachineType, MaintenanceType, MaintenanceStatus } from '@/features/machines/types';

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'machine-1',
    name: 'CNC Machine #1',
    model: 'CNC-5000X',
    manufacturer: 'Haas Automation',
    type: MachineType.CNC,
    status: MachineStatus.RUNNING,
    capacity: 100,
    location: 'Production Floor A',
    purchaseDate: '2022-01-15',
    installationDate: '2022-02-01',
    warrantyExpiry: '2025-01-15',
    lastMaintenanceDate: '2024-09-15',
    nextMaintenanceDate: '2024-12-15',
    description: 'High-precision CNC machining center for complex parts',
    specifications: {
      maxSpindleSpeed: 12000,
      toolCapacity: 24,
      workAreaX: 1000,
      workAreaY: 500,
      workAreaZ: 500,
      power: 15,
    },
    industryId: 'industry-1',
    createdAt: '2022-01-15T10:00:00Z',
    updatedAt: '2024-10-20T14:30:00Z',
    metrics: {
      utilization: 87,
      efficiency: 94,
      totalRuntime: 5240,
      totalDowntime: 120,
      averageUptime: 97.8,
      mtbf: 720,
      mttr: 4,
      productionCount: 12450,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-2',
    name: 'Lathe Machine #2',
    model: 'LT-2500',
    manufacturer: 'DMG MORI',
    type: MachineType.LATHE,
    status: MachineStatus.RUNNING,
    capacity: 80,
    location: 'Production Floor A',
    purchaseDate: '2021-06-20',
    installationDate: '2021-07-10',
    warrantyExpiry: '2024-06-20',
    lastMaintenanceDate: '2024-08-22',
    nextMaintenanceDate: '2024-11-22',
    description: 'Precision lathe for turning operations',
    specifications: {
      maxSpindleSpeed: 8000,
      maxTurningDiameter: 450,
      maxTurningLength: 1000,
      power: 11,
    },
    industryId: 'industry-1',
    createdAt: '2021-06-20T09:00:00Z',
    updatedAt: '2024-10-20T15:00:00Z',
    metrics: {
      utilization: 82,
      efficiency: 91,
      totalRuntime: 7850,
      totalDowntime: 180,
      averageUptime: 97.7,
      mtbf: 680,
      mttr: 5,
      productionCount: 18220,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-3',
    name: 'Drill Press #3',
    model: 'DP-1000',
    manufacturer: 'Makino',
    type: MachineType.DRILL,
    status: MachineStatus.IDLE,
    capacity: 60,
    location: 'Production Floor B',
    purchaseDate: '2020-03-10',
    installationDate: '2020-04-01',
    lastMaintenanceDate: '2024-10-10',
    nextMaintenanceDate: '2025-01-10',
    description: 'Industrial drilling machine for precision holes',
    specifications: {
      maxDrillDiameter: 50,
      spindleTravel: 300,
      power: 7.5,
    },
    industryId: 'industry-1',
    createdAt: '2020-03-10T11:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
    metrics: {
      utilization: 65,
      efficiency: 88,
      totalRuntime: 9120,
      totalDowntime: 210,
      averageUptime: 97.7,
      mtbf: 650,
      mttr: 6,
      productionCount: 24500,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-4',
    name: 'Milling Machine #4',
    model: 'VM-3000',
    manufacturer: 'Okuma',
    type: MachineType.MILL,
    status: MachineStatus.RUNNING,
    capacity: 90,
    location: 'Production Floor A',
    purchaseDate: '2022-08-15',
    installationDate: '2022-09-01',
    warrantyExpiry: '2025-08-15',
    lastMaintenanceDate: '2024-09-30',
    nextMaintenanceDate: '2024-12-30',
    description: 'Vertical milling machine for complex geometries',
    specifications: {
      maxSpindleSpeed: 10000,
      toolCapacity: 20,
      tableSize: '1500x600',
      power: 12,
    },
    industryId: 'industry-1',
    createdAt: '2022-08-15T13:00:00Z',
    updatedAt: '2024-10-20T16:00:00Z',
    metrics: {
      utilization: 90,
      efficiency: 96,
      totalRuntime: 4200,
      totalDowntime: 80,
      averageUptime: 98.1,
      mtbf: 750,
      mttr: 3,
      productionCount: 9800,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-5',
    name: 'Grinder #5',
    model: 'SG-800',
    manufacturer: 'Studer',
    type: MachineType.GRINDER,
    status: MachineStatus.MAINTENANCE,
    capacity: 50,
    location: 'Production Floor B',
    purchaseDate: '2019-11-20',
    installationDate: '2019-12-15',
    lastMaintenanceDate: '2024-10-18',
    nextMaintenanceDate: '2024-10-25',
    description: 'Surface grinding machine for finishing operations',
    specifications: {
      grindingWheel: 400,
      tableSize: '800x400',
      power: 9,
    },
    industryId: 'industry-1',
    createdAt: '2019-11-20T10:00:00Z',
    updatedAt: '2024-10-18T08:00:00Z',
    metrics: {
      utilization: 75,
      efficiency: 89,
      totalRuntime: 11200,
      totalDowntime: 280,
      averageUptime: 97.5,
      mtbf: 600,
      mttr: 7,
      productionCount: 32000,
      lastProductionDate: '2024-10-17',
    },
  },
  {
    id: 'machine-6',
    name: 'Press Machine #6',
    model: 'HP-500',
    manufacturer: 'Schuler',
    type: MachineType.PRESS,
    status: MachineStatus.RUNNING,
    capacity: 120,
    location: 'Production Floor C',
    purchaseDate: '2023-02-10',
    installationDate: '2023-03-01',
    warrantyExpiry: '2026-02-10',
    lastMaintenanceDate: '2024-10-05',
    nextMaintenanceDate: '2025-01-05',
    description: 'Hydraulic press for stamping and forming',
    specifications: {
      pressureCapacity: 500,
      strokeLength: 300,
      bedSize: '1200x800',
      power: 22,
    },
    industryId: 'industry-1',
    createdAt: '2023-02-10T12:00:00Z',
    updatedAt: '2024-10-20T17:00:00Z',
    metrics: {
      utilization: 85,
      efficiency: 93,
      totalRuntime: 3100,
      totalDowntime: 60,
      averageUptime: 98.1,
      mtbf: 800,
      mttr: 2,
      productionCount: 15600,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-7',
    name: 'Welding Machine #7',
    model: 'WM-350',
    manufacturer: 'Lincoln Electric',
    type: MachineType.WELDING,
    status: MachineStatus.IDLE,
    capacity: 70,
    location: 'Assembly Area',
    purchaseDate: '2021-09-15',
    installationDate: '2021-10-01',
    warrantyExpiry: '2024-09-15',
    lastMaintenanceDate: '2024-09-01',
    nextMaintenanceDate: '2024-12-01',
    description: 'Robotic welding station for automated joining',
    specifications: {
      weldingCurrent: 350,
      dutyCycle: 100,
      power: 18,
    },
    industryId: 'industry-1',
    createdAt: '2021-09-15T14:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
    metrics: {
      utilization: 72,
      efficiency: 90,
      totalRuntime: 6850,
      totalDowntime: 150,
      averageUptime: 97.9,
      mtbf: 700,
      mttr: 4,
      productionCount: 8900,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-8',
    name: 'Cutting Machine #8',
    model: 'LC-6000',
    manufacturer: 'Bystronic',
    type: MachineType.CUTTING,
    status: MachineStatus.RUNNING,
    capacity: 95,
    location: 'Production Floor C',
    purchaseDate: '2022-11-20',
    installationDate: '2022-12-10',
    warrantyExpiry: '2025-11-20',
    lastMaintenanceDate: '2024-09-20',
    nextMaintenanceDate: '2024-12-20',
    description: 'Laser cutting machine for sheet metal',
    specifications: {
      laserPower: 6000,
      cuttingArea: '3000x1500',
      maxThickness: 25,
      power: 30,
    },
    industryId: 'industry-1',
    createdAt: '2022-11-20T10:00:00Z',
    updatedAt: '2024-10-20T15:30:00Z',
    metrics: {
      utilization: 88,
      efficiency: 95,
      totalRuntime: 3950,
      totalDowntime: 70,
      averageUptime: 98.2,
      mtbf: 780,
      mttr: 3,
      productionCount: 11200,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-9',
    name: 'Assembly Line #9',
    model: 'AL-2000',
    manufacturer: 'Bosch Rexroth',
    type: MachineType.ASSEMBLY,
    status: MachineStatus.RUNNING,
    capacity: 150,
    location: 'Assembly Area',
    purchaseDate: '2023-05-10',
    installationDate: '2023-06-01',
    warrantyExpiry: '2026-05-10',
    lastMaintenanceDate: '2024-10-01',
    nextMaintenanceDate: '2025-01-01',
    description: 'Automated assembly line for product assembly',
    specifications: {
      lineSpeed: 20,
      stations: 12,
      power: 25,
    },
    industryId: 'industry-1',
    createdAt: '2023-05-10T09:00:00Z',
    updatedAt: '2024-10-20T18:00:00Z',
    metrics: {
      utilization: 92,
      efficiency: 97,
      totalRuntime: 2800,
      totalDowntime: 40,
      averageUptime: 98.6,
      mtbf: 850,
      mttr: 2,
      productionCount: 42000,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-10',
    name: 'Packaging Machine #10',
    model: 'PM-1500',
    manufacturer: 'Ishida',
    type: MachineType.PACKAGING,
    status: MachineStatus.RUNNING,
    capacity: 110,
    location: 'Packaging Area',
    purchaseDate: '2023-08-15',
    installationDate: '2023-09-01',
    warrantyExpiry: '2026-08-15',
    lastMaintenanceDate: '2024-10-10',
    nextMaintenanceDate: '2025-01-10',
    description: 'Automated packaging system for finished products',
    specifications: {
      packagingSpeed: 150,
      bagSize: '100-500g',
      power: 12,
    },
    industryId: 'industry-1',
    createdAt: '2023-08-15T11:00:00Z',
    updatedAt: '2024-10-20T16:30:00Z',
    metrics: {
      utilization: 86,
      efficiency: 94,
      totalRuntime: 2400,
      totalDowntime: 50,
      averageUptime: 98.0,
      mtbf: 820,
      mttr: 2,
      productionCount: 36000,
      lastProductionDate: '2024-10-20',
    },
  },
  {
    id: 'machine-11',
    name: 'CNC Machine #11',
    model: 'CNC-3000',
    manufacturer: 'Mazak',
    type: MachineType.CNC,
    status: MachineStatus.IDLE,
    capacity: 85,
    location: 'Production Floor A',
    purchaseDate: '2020-12-10',
    installationDate: '2021-01-15',
    lastMaintenanceDate: '2024-08-15',
    nextMaintenanceDate: '2024-11-15',
    description: 'Multi-axis CNC machine for precision parts',
    specifications: {
      maxSpindleSpeed: 10000,
      toolCapacity: 20,
      axes: 5,
      power: 13,
    },
    industryId: 'industry-1',
    createdAt: '2020-12-10T10:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
    metrics: {
      utilization: 78,
      efficiency: 92,
      totalRuntime: 8200,
      totalDowntime: 200,
      averageUptime: 97.6,
      mtbf: 680,
      mttr: 5,
      productionCount: 16500,
      lastProductionDate: '2024-10-19',
    },
  },
  {
    id: 'machine-12',
    name: 'Test Machine #12',
    model: 'TEST-100',
    manufacturer: 'Generic',
    type: MachineType.OTHER,
    status: MachineStatus.OFFLINE,
    capacity: 40,
    location: 'Storage',
    purchaseDate: '2018-05-20',
    description: 'Reserved for testing and development',
    industryId: 'industry-1',
    createdAt: '2018-05-20T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
    metrics: {
      utilization: 0,
      efficiency: 0,
      totalRuntime: 0,
      totalDowntime: 0,
      averageUptime: 0,
      productionCount: 0,
    },
  },
];

export const MOCK_MACHINE_STATS: MachineStats = {
  total: 12,
  running: 7,
  idle: 3,
  maintenance: 1,
  offline: 1,
  averageUtilization: 83.5,
  averageEfficiency: 92.4,
};

export const MOCK_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    machineId: 'machine-1',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-09-15',
    completedDate: '2024-09-15',
    description: 'Routine preventive maintenance - lubrication and inspection',
    performedBy: 'Maintenance Team A',
    cost: 500,
    notes: 'All systems operating normally',
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-09-15T16:00:00Z',
  },
  {
    id: 'maint-2',
    machineId: 'machine-1',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-12-15',
    description: 'Scheduled quarterly maintenance',
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'maint-3',
    machineId: 'machine-2',
    type: MaintenanceType.CORRECTIVE,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-08-22',
    completedDate: '2024-08-22',
    description: 'Spindle bearing replacement',
    performedBy: 'Maintenance Team B',
    cost: 1200,
    notes: 'Bearing replaced, machine recalibrated',
    createdAt: '2024-08-20T09:00:00Z',
    updatedAt: '2024-08-22T17:00:00Z',
  },
  {
    id: 'maint-4',
    machineId: 'machine-5',
    type: MaintenanceType.PREVENTIVE,
    status: MaintenanceStatus.IN_PROGRESS,
    scheduledDate: '2024-10-18',
    description: 'Grinding wheel replacement and alignment',
    performedBy: 'Maintenance Team A',
    createdAt: '2024-10-10T10:00:00Z',
    updatedAt: '2024-10-18T08:00:00Z',
  },
  {
    id: 'maint-5',
    machineId: 'machine-5',
    type: MaintenanceType.SCHEDULED,
    status: MaintenanceStatus.PENDING,
    scheduledDate: '2024-10-25',
    description: 'Post-maintenance inspection and testing',
    createdAt: '2024-10-18T10:00:00Z',
    updatedAt: '2024-10-18T10:00:00Z',
  },
  {
    id: 'maint-6',
    machineId: 'machine-4',
    type: MaintenanceType.EMERGENCY,
    status: MaintenanceStatus.COMPLETED,
    scheduledDate: '2024-07-10',
    completedDate: '2024-07-10',
    description: 'Emergency repair - coolant leak',
    performedBy: 'Maintenance Team C',
    cost: 800,
    notes: 'Coolant hose replaced, system tested',
    createdAt: '2024-07-10T14:00:00Z',
    updatedAt: '2024-07-10T18:00:00Z',
  },
];

// ====================
// SYSTEM ADMIN DATA
// ====================

// Industries
import type {
  Industry,
  Subscription,
  PlatformAnalytics,
  PlatformMetrics,
  SubscriptionDistribution,
  RevenueData,
  IndustryGrowth,
  TopIndustry,
} from '@/features/system/types';
import { IndustryStatus, SubscriptionPlan, SubscriptionStatus } from '@/features/system/types';

export const MOCK_INDUSTRIES: Industry[] = [
  {
    id: 'industry-1',
    name: 'Precision Manufacturing Co.',
    description: 'High-precision CNC machining and manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.ENTERPRISE,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Factory Owner',
    adminEmail: 'owner@factory1.com',
    phoneNumber: '+1-555-0101',
    address: '123 Industrial Avenue',
    city: 'Detroit',
    state: 'Michigan',
    country: 'USA',
    postalCode: '48201',
    employeeCount: 156,
    machineCount: 12,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
    expiryDate: '2025-01-15T00:00:00Z',
  },
  {
    id: 'industry-2',
    name: 'AutoTech Industries',
    description: 'Automotive parts manufacturing and assembly',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.PROFESSIONAL,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'John Smith',
    adminEmail: 'admin@autotech.com',
    phoneNumber: '+1-555-0102',
    address: '456 Manufacturing Blvd',
    city: 'Chicago',
    state: 'Illinois',
    country: 'USA',
    postalCode: '60601',
    employeeCount: 98,
    machineCount: 8,
    createdAt: '2023-03-20T08:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
    expiryDate: '2025-03-20T00:00:00Z',
  },
  {
    id: 'industry-3',
    name: 'Metal Works Ltd.',
    description: 'Metal fabrication and welding services',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.BASIC,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Sarah Johnson',
    adminEmail: 'admin@metalworks.com',
    phoneNumber: '+1-555-0103',
    address: '789 Steel Street',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    country: 'USA',
    postalCode: '15201',
    employeeCount: 45,
    machineCount: 5,
    createdAt: '2023-06-10T08:00:00Z',
    updatedAt: '2024-08-20T10:00:00Z',
    expiryDate: '2025-06-10T00:00:00Z',
  },
  {
    id: 'industry-4',
    name: 'Tech Components Inc.',
    description: 'Electronic component manufacturing',
    status: IndustryStatus.SUSPENDED,
    subscriptionPlan: SubscriptionPlan.PROFESSIONAL,
    subscriptionStatus: SubscriptionStatus.PAYMENT_PENDING,
    adminName: 'Michael Chen',
    adminEmail: 'admin@techcomponents.com',
    phoneNumber: '+1-555-0104',
    address: '321 Tech Park',
    city: 'San Jose',
    state: 'California',
    country: 'USA',
    postalCode: '95101',
    employeeCount: 72,
    machineCount: 6,
    createdAt: '2023-08-05T08:00:00Z',
    updatedAt: '2024-10-10T10:00:00Z',
    expiryDate: '2024-08-05T00:00:00Z',
  },
  {
    id: 'industry-5',
    name: 'Aerospace Solutions',
    description: 'Aerospace component manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.ENTERPRISE,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    adminName: 'Robert Williams',
    adminEmail: 'admin@aerospace.com',
    phoneNumber: '+1-555-0105',
    address: '555 Aviation Way',
    city: 'Seattle',
    state: 'Washington',
    country: 'USA',
    postalCode: '98101',
    employeeCount: 210,
    machineCount: 15,
    createdAt: '2022-11-01T08:00:00Z',
    updatedAt: '2024-09-25T10:00:00Z',
    expiryDate: '2025-11-01T00:00:00Z',
  },
  {
    id: 'industry-6',
    name: 'Polymer Products',
    description: 'Plastic injection molding and manufacturing',
    status: IndustryStatus.ACTIVE,
    subscriptionPlan: SubscriptionPlan.BASIC,
    subscriptionStatus: SubscriptionStatus.TRIAL,
    adminName: 'Emily Davis',
    adminEmail: 'admin@polymer.com',
    phoneNumber: '+1-555-0106',
    address: '888 Polymer Lane',
    city: 'Houston',
    state: 'Texas',
    country: 'USA',
    postalCode: '77001',
    employeeCount: 38,
    machineCount: 4,
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
    expiryDate: '2024-10-15T00:00:00Z',
  },
];

// Subscriptions
export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    industryId: 'industry-1',
    industryName: 'Precision Manufacturing Co.',
    plan: SubscriptionPlan.ENTERPRISE,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-01-15T00:00:00Z',
    endDate: '2025-01-15T00:00:00Z',
    maxUsers: 200,
    maxMachines: 50,
    maxStorage: 1000,
    currentUsers: 156,
    currentMachines: 12,
    currentStorage: 234,
    features: [
      'Unlimited Users',
      'Advanced Analytics',
      'Priority Support',
      'Custom Integrations',
      'API Access',
      'White Label',
    ],
    price: 999,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'sub-2',
    industryId: 'industry-2',
    industryName: 'AutoTech Industries',
    plan: SubscriptionPlan.PROFESSIONAL,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-03-20T00:00:00Z',
    endDate: '2025-03-20T00:00:00Z',
    maxUsers: 100,
    maxMachines: 25,
    maxStorage: 500,
    currentUsers: 98,
    currentMachines: 8,
    currentStorage: 156,
    features: [
      'Up to 100 Users',
      'Standard Analytics',
      'Email Support',
      'API Access',
    ],
    price: 499,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-03-20T08:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'sub-3',
    industryId: 'industry-3',
    industryName: 'Metal Works Ltd.',
    plan: SubscriptionPlan.BASIC,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-06-10T00:00:00Z',
    endDate: '2025-06-10T00:00:00Z',
    maxUsers: 50,
    maxMachines: 10,
    maxStorage: 100,
    currentUsers: 45,
    currentMachines: 5,
    currentStorage: 42,
    features: [
      'Up to 50 Users',
      'Basic Analytics',
      'Email Support',
    ],
    price: 199,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2023-06-10T08:00:00Z',
    updatedAt: '2024-08-20T10:00:00Z',
  },
  {
    id: 'sub-4',
    industryId: 'industry-4',
    industryName: 'Tech Components Inc.',
    plan: SubscriptionPlan.PROFESSIONAL,
    status: SubscriptionStatus.PAYMENT_PENDING,
    startDate: '2023-08-05T00:00:00Z',
    endDate: '2024-08-05T00:00:00Z',
    maxUsers: 100,
    maxMachines: 25,
    maxStorage: 500,
    currentUsers: 72,
    currentMachines: 6,
    currentStorage: 89,
    features: [
      'Up to 100 Users',
      'Standard Analytics',
      'Email Support',
      'API Access',
    ],
    price: 499,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: false,
    createdAt: '2023-08-05T08:00:00Z',
    updatedAt: '2024-10-10T10:00:00Z',
  },
  {
    id: 'sub-5',
    industryId: 'industry-5',
    industryName: 'Aerospace Solutions',
    plan: SubscriptionPlan.ENTERPRISE,
    status: SubscriptionStatus.ACTIVE,
    startDate: '2024-11-01T00:00:00Z',
    endDate: '2025-11-01T00:00:00Z',
    maxUsers: 200,
    maxMachines: 50,
    maxStorage: 1000,
    currentUsers: 210,
    currentMachines: 15,
    currentStorage: 456,
    features: [
      'Unlimited Users',
      'Advanced Analytics',
      'Priority Support',
      'Custom Integrations',
      'API Access',
      'White Label',
    ],
    price: 999,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: true,
    createdAt: '2022-11-01T08:00:00Z',
    updatedAt: '2024-09-25T10:00:00Z',
  },
  {
    id: 'sub-6',
    industryId: 'industry-6',
    industryName: 'Polymer Products',
    plan: SubscriptionPlan.BASIC,
    status: SubscriptionStatus.TRIAL,
    startDate: '2024-09-15T00:00:00Z',
    endDate: '2024-10-15T00:00:00Z',
    maxUsers: 50,
    maxMachines: 10,
    maxStorage: 100,
    currentUsers: 38,
    currentMachines: 4,
    currentStorage: 12,
    features: [
      'Up to 50 Users',
      'Basic Analytics',
      'Email Support',
    ],
    price: 0,
    currency: 'USD',
    billingCycle: 'monthly',
    autoRenew: false,
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
];

// Platform Analytics
const platformMetrics: PlatformMetrics = {
  totalIndustries: 6,
  activeIndustries: 5,
  totalUsers: 619,
  totalMachines: 50,
  totalRevenue: 189420,
  monthlyRevenue: 3196,
  totalStorage: 989,
  totalOrders: 1247,
};

const subscriptionDistribution: SubscriptionDistribution[] = [
  {
    plan: SubscriptionPlan.FREE,
    count: 0,
    percentage: 0,
    revenue: 0,
  },
  {
    plan: SubscriptionPlan.BASIC,
    count: 2,
    percentage: 33.3,
    revenue: 398,
  },
  {
    plan: SubscriptionPlan.PROFESSIONAL,
    count: 2,
    percentage: 33.3,
    revenue: 998,
  },
  {
    plan: SubscriptionPlan.ENTERPRISE,
    count: 2,
    percentage: 33.3,
    revenue: 1998,
  },
];

const revenueData: RevenueData[] = [
  { month: 'Jan', revenue: 15680, subscriptions: 4 },
  { month: 'Feb', revenue: 16240, subscriptions: 4 },
  { month: 'Mar', revenue: 18790, subscriptions: 5 },
  { month: 'Apr', revenue: 17650, subscriptions: 5 },
  { month: 'May', revenue: 19230, subscriptions: 5 },
  { month: 'Jun', revenue: 21450, subscriptions: 6 },
  { month: 'Jul', revenue: 19870, subscriptions: 6 },
  { month: 'Aug', revenue: 18340, subscriptions: 5 },
  { month: 'Sep', revenue: 20560, subscriptions: 6 },
  { month: 'Oct', revenue: 19180, subscriptions: 6 },
  { month: 'Nov', revenue: 16240, subscriptions: 5 },
  { month: 'Dec', revenue: 15680, subscriptions: 5 },
];

const industryGrowth: IndustryGrowth[] = [
  { month: 'Jan', newIndustries: 0, activeIndustries: 4, churnedIndustries: 0 },
  { month: 'Feb', newIndustries: 0, activeIndustries: 4, churnedIndustries: 0 },
  { month: 'Mar', newIndustries: 1, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'Apr', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'May', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
  { month: 'Jun', newIndustries: 1, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Jul', newIndustries: 0, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Aug', newIndustries: 0, activeIndustries: 5, churnedIndustries: 1 },
  { month: 'Sep', newIndustries: 1, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Oct', newIndustries: 0, activeIndustries: 6, churnedIndustries: 0 },
  { month: 'Nov', newIndustries: 0, activeIndustries: 5, churnedIndustries: 1 },
  { month: 'Dec', newIndustries: 0, activeIndustries: 5, churnedIndustries: 0 },
];

const topIndustries: TopIndustry[] = [
  {
    id: 'industry-5',
    name: 'Aerospace Solutions',
    plan: SubscriptionPlan.ENTERPRISE,
    users: 210,
    machines: 15,
    revenue: 11988,
  },
  {
    id: 'industry-1',
    name: 'Precision Manufacturing Co.',
    plan: SubscriptionPlan.ENTERPRISE,
    users: 156,
    machines: 12,
    revenue: 11988,
  },
  {
    id: 'industry-2',
    name: 'AutoTech Industries',
    plan: SubscriptionPlan.PROFESSIONAL,
    users: 98,
    machines: 8,
    revenue: 5988,
  },
  {
    id: 'industry-4',
    name: 'Tech Components Inc.',
    plan: SubscriptionPlan.PROFESSIONAL,
    users: 72,
    machines: 6,
    revenue: 5988,
  },
  {
    id: 'industry-3',
    name: 'Metal Works Ltd.',
    plan: SubscriptionPlan.BASIC,
    users: 45,
    machines: 5,
    revenue: 2388,
  },
];

export const MOCK_PLATFORM_ANALYTICS: PlatformAnalytics = {
  metrics: platformMetrics,
  subscriptionDistribution,
  revenueData,
  industryGrowth,
  topIndustries,
};
